### ISSUE TITLE
ResourceDisk.Format option on Ubuntu

### ISSUE THREAD

**Issue by johanburati** [Azure/WALinuxAgent#1003]
On the Ubuntu marketplace images the resource disk gets formatted during deployment and is mounted from the _/etc/fstab_ file, the **ResourceDisk.Format** option is set to **n** by default in the _/etc/waagent.conf_ file.

```
# Format if unformatted. If 'n', resource disk will not be mounted.
ResourceDisk.Format=n
```
It seems there is a dependency between **ResourceDisk.Format** and the swap file, if **ResourceDisk.Format** is set to **n** and **ResourceDisk.EnableSwap** is set to **y**, then the swap file will not be created even if the resource disk is already mounted from the _/etc/fstab_ file.

It would be better if the agent could check if the resource disk is actually mounted or not and create/activate the swap file based on this and not rely on the value of the **ResourceDisk.Format** option. Also renaming **ResourceDisk.Format** to **ResourceDisk.Mount** would make more sense IMHO since that option indicate that the agent will take care of mounting the resource disk (of course the agent would still format the resource disk if it does not find a file system on the disk).

**Comment by boumenot** [comment]
I agree that the options are incompatible. 

There is a large dependency on these options because they have been in existence for years. I am hesitant to rename options at this point and change behavior.  This is the first time I have seen an issue raised, so I am closing the issue for now.  We can revisit if necessary in the future.
