### ISSUE TITLE
waagent can not provision instance

### ISSUE THREAD

**Issue by chubin** [Azure/WALinuxAgent#1032]
I'm trying to build my own Linux image with Azure agent.
The problem is that the Agent does not do provisioning:
```
2018/02/04 22:45:40 Provisioning image started.
2018/02/04 22:45:43 ERROR:CalledProcessError.  Error Code is 1
2018/02/04 22:45:43 ERROR:CalledProcessError.  Command string was LC_ALL=C fdisk -l /dev/sr0 | grep Disk
2018/02/04 22:45:43 ERROR:CalledProcessError.  Command result was 
2018/02/04 22:45:43 Module /lib/modules/2.6.32-642.el6.x86_64/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
2018/02/04 22:45:59 ERROR:CalledProcessError.  Error Code is 32
2018/02/04 22:45:59 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2018/02/04 22:45:59 ERROR:CalledProcessError.  Command result was mount: you must specify the filesystem type
2018/02/04 22:45:59 mount: you must specify the filesystem type
2018/02/04 22:45:59 mount failed on attempt #1
2018/02/04 22:45:59 mount loop sleeping 5...
2018/02/04 22:46:19 ERROR:CalledProcessError.  Error Code is 32
2018/02/04 22:46:19 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2018/02/04 22:46:19 ERROR:CalledProcessError.  Command result was mount: you must specify the filesystem type
2018/02/04 22:46:19 mount: you must specify the filesystem type
2018/02/04 22:46:19 mount failed on attempt #2
2018/02/04 22:46:19 mount loop sleeping 5...
2018/02/04 22:46:39 ERROR:CalledProcessError.  Error Code is 32
2018/02/04 22:46:39 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2018/02/04 22:46:39 ERROR:CalledProcessError.  Command result was mount: you must specify the filesystem type
2018/02/04 22:46:39 mount: you must specify the filesystem type
2018/02/04 22:46:39 mount failed on attempt #3
2018/02/04 22:46:39 mount loop sleeping 5...
2018/02/04 22:46:59 ERROR:CalledProcessError.  Error Code is 32
2018/02/04 22:46:59 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2018/02/04 22:46:59 ERROR:CalledProcessError.  Command result was mount: you must specify the filesystem type
2018/02/04 22:46:59 mount: you must specify the filesystem type
2018/02/04 22:46:59 mount failed on attempt #4
2018/02/04 22:46:59 mount loop sleeping 5...
2018/02/04 22:47:20 ERROR:CalledProcessError.  Error Code is 32
2018/02/04 22:47:20 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2018/02/04 22:47:20 ERROR:CalledProcessError.  Command result was mount: you must specify the filesystem type
2018/02/04 22:47:20 mount: you must specify the filesystem type
2018/02/04 22:47:20 mount failed on attempt #5
2018/02/04 22:47:20 mount loop sleeping 5...
```

I use the last released agent version.

**Comment by hglkrijger** [comment]
The errors seem self-explanatory. If you are building a custom image most likely you will need a custom distro support class; you can find examples in the code.

**Comment by chubin** [comment]
Please reopen the issue. The issue still exists.
I don't use any custom distro, I use CentOS. 

May be the errors are self-explanatory for you but not for me.
The agent can't mount some image, that's true, but what Image?
It should be attached by the host system. Why it does not do it?

The agent doesn't work. Please reopen the issue.

**Comment by szarkos** [comment]
To me it looks like /dev/sr0 doesn't exist.

At first boot the agent tries to mount a DVD device, which contains a file (ovf-env.xml) that includes all the provisioning information for the instance (host name, username, password, ssh-key, user-data).  You will need to investigate why your instance cannot see or mount /dev/sr0.  To mount sr0 you will need ata_piix driver (which is there) and udf.ko.  Make sure the latter isn't blacklisted or missing.

Another thing to look at is how you are creating the VM.  In Azure you have either "specialized" VMs or "generalized".  Specialized means simply creating VM container on top of a VHD blob, i.e. when creating a VM from a snapshot.  Since the VM was already provisioned at one time then there will be no DVD device attached and no provisioning cycle.  In this case I suspect you want to create a VM from a generalized image.

Here is a template example to create a VM from a generalized image: https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-from-user-image

Or if using the Azure CLI you would run something like:

  $ azure vm create .... --image <VHD URI>

Note that there is also the "--attach-os-disk" parameter, which is what you would use to create a specialized VM.
