### ISSUE TITLE
feature request: configuration file option for disabling or white-listing extensions

### ISSUE THREAD

**Issue by eduda** [Azure/WALinuxAgent#1075]
Looking for a way to allow specific list of extensions or allow none to be deployed. Trying to make it so that users can't change anything in the OS via the extension tab in azure ui. For example,  :Custom Script for Linux", I need to make sure that this is never deployed to the VM because of security reasons.

**Comment by boumenot** [comment]
It doesn't make sense to do this at the level of the agent. The agent should do what it is told instead of making these types of decisions. Ideally, you should be able to configure this yourself using the existing permissions mechanism, but it does sound like that will work because you want to allow some extensions and deny others.

Here's an example of role assignment. You may be able to use this instead, but it would have to be an all or nothing deal.

```sh
$ azure role assignment create \
  --spn APPURL \
  -o "Owner" \
  -c /subscriptions/SUBSCRIPTIONID
```

The URL can be expanded to control for Resource Group or even VM.  You can prevent any writes to a particular VM for a given user or SPN.

**Comment by boumenot** [comment]
I stand corrected.  I spoke with @danielsollondon, and he said there is a way to do this today using RBAC policy.  He will update with a link to the document.

**Comment by eduda** [comment]
I agree in some cases, the agent should do what it's told but in this case, i need to lock down the VM OS and in my case, i can't use azure polices as those are outside of my control. I only have access to the OS in the VM. I'm fine with all or nothing for disabling the extensions.

**Comment by boumenot** [comment]
Sorry, it took a lot longer than expected to get the documents published.  Here are the first parts for PS and CLI.

 * https://docs.microsoft.com/en-us/azure/virtual-machines/windows/extensions-rmpolicy-howto-ps 
 * https://docs.microsoft.com/en-us/azure/virtual-machines/linux/extensions-rmpolicy-howto-cli

**Comment by eduda** [comment]
Thanks for the info. That's useful feature to restrict access, but in my case, it will not work as i don't have access to the azure subscription and have no way to add it. in my case, i'm looking to make sure my VM does not getting any extensions installed as it would break the VM at he OS level. thats why i thought walinuxagent patch would be the way to go to stop them from getting installed and have the agent return to the portal an error that says extensions are not allowed to be installed on this VM.
