### ISSUE TITLE
Output from executing CustomData is lost

### ISSUE THREAD

**Issue by gregjhogan** [Azure/WALinuxAgent#112]
When enabling Provisioning.ExecuteCustomData all output (stdin and stderr) is lost.  When executing the script fails it is difficult to figure out what happened unless you somehow log information to a custom location.  It would be nice if this output automatically went to /var/log/waagent.log.

**Comment by yuezh** [comment]
Thanks for reporting this to us. We will consider to fix it in our next version.

**Comment by ahmetalpbalkan** [comment]
It looks like this issue was never fixed, the agent still just invokes the script in the CustomData file and only if there's an error, there is some information in waagent.log.

I am not sure if this will be implemented or we will port the ability to execute CustomData in the new guest agent that we are coming up with. 

@gregjhogan what is the distro you are using? Ideally, `cloud-init` or `cloud-config` in the distro should be handling execution of CustomData.

**Comment by gregjhogan** [comment]
@ahmetalpbalkan I am using CentOS.  Has cloud-init support been added for CentOS?  Thanks!

**Comment by ahmetalpbalkan** [comment]
@gregjhogan I don't think so. Our plan is to add cloud-init support to as many distros as we can. There is already work going on to port cloud-init Azure modules to RHEL. CentOS will certainly benefit from that, too. I think we are not going to take a fix here in the `waagent` to have better output collection.

I suggest you to update your script in CustomData to start with 

```
exec >> file
exec 2>&1
```

so that the script logs its own output to a `file` you specify (e.g. /var/log/customdata.log).
