### ISSUE TITLE
wagent using deprecated route commands

### ISSUE THREAD

**Issue by shemminger** [Azure/WALinuxAgent#1155]
The wagent2.0 script is still using deprecated /sbin/route commands. It should be using ip route.

**Comment by boumenot** [comment]
Are you seeing this in use, or did you just observe this while reading the code?

WALA does not use waaagent2.0 or waagent, but we ship them because some extensions still uses these scripts for pieces of their functionality. We have been trying to undo that, but there are still versions in the wild that have this behavior.  I believe the functionality used is **mostly** limited to telemetry and logging.

**Comment by shemminger** [comment]
On Tue, 08 May 2018 16:48:55 +0000 (UTC)
Christopher Boumenot <notifications@github.com> wrote:

> Are you seeing this in use, or did you just observe this while reading the code?

No just reading code.

> 
> WALA does not use waaagent2.0 or waagent, but we ship them because some extensions still uses these scripts for pieces of their functionality. We have been trying to undo that, but there are still versions in the wild that have this behavior.  I believe the functionality used is **mostly** limited to telemetry and logging.
> 
>

**Comment by hglkrijger** [comment]
Closing, since waagent2.0 is not in use.
