### ISSUE TITLE
WALA should create user in an early stage when provisioning Azure Linux VM

### ISSUE THREAD

**Issue by simonxiaoss** [Azure/WALinuxAgent#1157]
I saw cases that the Azure Linux VM provisioning failed because of dhcp address is not assigned to the NIC. In such cases, I hope I can login the VM and do bunch of checks for example, udev rules, ifconfig, etc.
But currently, WALA will stuck there and keep trying dhcp silently ("WARNING Primary interface examination will retry silently") so the user creation step will not be executed. Hence I am not able to login the VM for checking from Azure serial console.
So, please move the user creation to an early stage and make it take effect as early as possible.

**Comment by szarkos** [comment]
This is probably a bigger can of worms than one might think. The provisioning agent requires network connectivity for several things:

   - Obtain SSH key from certificates XML
   - Set up hostname configuration for primary interface
   - Report ready to the fabric

The agent would have to go as far as it could to provision and then loop after user creation to wait for the network.  This would also only be helpful for system users created with a password, which is generally not something we encourage.

But that alone would not be sufficient on some systems such as SLES or RHEL, which need to first activate themselves and register the system with SUSE or Red Hat to access their package repositories hosted in Azure.  The reason is because the Azure Agent also includes a goalstate agent to run VM extensions.  Some extensions such as CustomScript might install packages and set up workloads - so networking, VM registration and access to package repositories is required before even starting the Azure agent service.

So to make this scenario work the agent would need to be split up into multiple services, at least two - one for provisioning that can run very early in boot, and another for processing VM extensions.  The Debian folks have done this by creating multiple entry points and services for provisioning and extension handling. This could be generalized for other distros as well.

**Comment by hglkrijger** [comment]
We are not going to make any changes here.
