### ISSUE TITLE
WALinuxAgent-2.2.14 high CPU utilization

### ISSUE THREAD

**Issue by ellahikamran** [Azure/WALinuxAgent#1177]
Waagent taking up 27% of CPU utilization, we are running the following version of WA Agent

WALinuxAgent-2.2.14 running on debian 8.10
Python: 3.4.2
Goal state agent: b'2.2.20'

**Comment by johnstsimoes** [comment]
We're just migrating to Azure from AWS and noticed this as well.

Debian 8.10
Python 3.4.2
python3 -u bin/WALinuxAgent-2.2.26-py2.7.egg -run-exthandlers

**Comment by boumenot** [comment]
How are you observing the CPU usage? Is it constant? Is it spikey? What is your VM sku?

We are doing some work to help address this, but it is going to be over the next two releases.  We are going to start enforcing CPU limits on the agent to better control its behavior.

**Comment by ellahikamran** [comment]
@johnstsimoes i upgraded to 2.2.25 which solved the problem for me . 
this is what i did 
cd /var/lib/waagent
wget https://github.com/Azure/WALinuxAgent/archive/v2.2.25.zip
unzip v2.2.25.zip
cd WALinuxAgent-2.2.25
sudo python setup.py install
sudo service walinuxagent restart

**Comment by tvvignesh** [comment]
I am using version 2.2.25 and close to 50% of the CPU is taken by waagent in an abnormal fashion (varying load). A fix is needed to this asap.

**Comment by danielsollondon** [comment]
@tvvignesh - which version of centos are you seeing this on?

**Comment by tvvignesh** [comment]
@danielsollondon The version is CentOS Linux release 7.4.1708 (Core)

And below are some screenshots which show the same.

![pastedimage](https://user-images.githubusercontent.com/1165845/42200406-ae932ba6-7eb0-11e8-8802-5213a3a42d48.png)

![pastedimage 1](https://user-images.githubusercontent.com/1165845/42200411-b2979390-7eb0-11e8-9552-bee1741ded2f.png)

![pastedimage 2](https://user-images.githubusercontent.com/1165845/42200415-b67c83b2-7eb0-11e8-92ce-fc0d96533a80.png)

**Comment by hglkrijger** [comment]
@tvvignesh do you have any extensions installed or attempting to install on this VM?

**Comment by tvvignesh** [comment]
@hglkrijger We are using the VM as is from Azure. Have not added any extensions to it.

**Comment by tvvignesh** [comment]
@danielsollondon @hglkrijger Is there any resolution or workaround to this? I am not sure if there is any way to disable WALinuxAgent. 

WALinuxAgent-2.2.26 running on centos 7.4.1708
Python: 2.7.5
Goal state agent: 2.2.26

**Comment by hglkrijger** [comment]
@tvvignesh could you verify that there are no extensions installed? There are various ways they can get installed through interactions with the portal or as part of a marketplace image. You can do this by:

- looking at the VM overview blade on the portal
- looking in `/var/lib/waagent` for extension folders (you can just send us the output of `ls -l /var/lib/waagent`)

We also have some upcoming features to try and help with these situations.

**Comment by tvvignesh** [comment]
@hglkrijger Thanks for your reply. I have added the output of /var/lib/waagent below. I will ask my sys admin once again if there are any extensions installed. Maybe there is something we are doing wrong but not sure what.

After seeing the output below, I am assuming there are pre-installed extensions (not sure since we did not install any extension manually after getting the VM) but I will check with my sys admin again for the same.

`
[ramcoazure@HCMDEMAZIND01 waagent]$ ls -l 

total 162312
-r--------   1 root root      1314 Jul 17 10:08 4CB9409BABB4672BD128243F11B0A3160549954F.crt
-r--------   1 root root      1860 Jul 17 10:08 4CB9409BABB4672BD128243F11B0A3160549954F.prv
-r--------.  1 root root      4091 Jul 17 10:08 Certificates.p7m
-r--------.  1 root root      3174 Jul 17 10:08 Certificates.pem
-rw-r--r--.  1 root root      4249 Jul 17 10:08 Certificates.xml
-rw-r--r--   1 root root        32 Jul 29 14:35 current_version
drwx------.  2 root root     65536 Aug  4 06:04 events
-rw-r--r--   1 root root       160 Jul  2 18:48 event_status.json
-rw-r--r--.  1 root root     18436 Feb 26 11:36 ExtensionsConfig.1.xml
-rw-r--r--.  1 root root     18754 Jul 17 10:08 ExtensionsConfig.2.xml
-rw-r--r--.  1 root root     30135 Aug  4  2017 ExtensionsConfig.3.xml
-rw-r--r--.  1 root root     18436 Oct 13  2017 ExtensionsConfig.4.xml
-rw-r--r--.  1 root root     28104 Mar 21  2017 ExtensionsConfig.5.xml
-rw-r--r--.  1 root root     28104 Mar 21  2017 ExtensionsConfig.6.xml
-rw-r--r--.  1 root root     28104 Mar 21  2017 ExtensionsConfig.7.xml
-rw-r--r--   1 root root     28104 Apr 22  2017 ExtensionsConfig.8.xml
-rw-r--r--.  1 root root      1965 Feb 26 11:36 GoalState.1.xml
-rw-r--r--.  1 root root      1965 Jul 17 10:08 GoalState.2.xml
-rw-r--r--.  1 root root      1965 Aug  4  2017 GoalState.3.xml
-rw-r--r--.  1 root root      1965 Oct 13  2017 GoalState.4.xml
-rw-r--r--.  1 root root      2032 Mar 21  2017 GoalState.5.xml
-rw-r--r--.  1 root root      2032 Mar 21  2017 GoalState.6.xml
-rw-r--r--.  1 root root      2033 Mar 21  2017 GoalState.7.xml
-rw-r--r--   1 root root      1966 Apr 22  2017 GoalState.8.xml
-rw-r--r--.  1 root root      1934 Jul 17 10:08 HostingEnvironmentConfig.xml
-rw-r--r--   1 root root         1 Jul 17 10:08 Incarnation
-rw-r--r--   1 root root      3188 Jun 28  2017 Microsoft.Azure.Extensions.LinuxAsm.1.manifest
-rw-r--r--   1 root root      3521 May  3 06:27 Microsoft.Azure.Extensions.LinuxAsm.1.manifest.xml
-rw-r--r--.  1 root root      2189 Jan 17  2017 Microsoft.Azure.Extensions.LinuxAsm.2.manifest
-rw-r--r--   1 root root      3521 Aug  4 06:04 Microsoft.Azure.Extensions.LinuxAsm.2.manifest.xml
-rw-r--r--   1 root root      3521 Jul 26  2017 Microsoft.Azure.Extensions.LinuxAsm.3.manifest
drwxr-xr-x   6 root root      4096 Mar  8 00:05 Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.60.2
-rw-r--r--   1 root root 164757364 Aug  4 06:04 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.6.42.0.zip
-rw-r--r--   1 root root      7198 May  3 06:27 Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux.1.manifest.xml
-rw-r--r--   1 root root      7198 Aug  4 06:04 Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux.2.manifest.xml
-rw-r--r--   1 root root      2455 Jul 26  2017 Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux.3.manifest
-rw-r--r--   1 root root      3605 Aug  8  2017 Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux.4.manifest
-rw-r--r--.  1 root root      1935 Apr 24  2017 Microsoft.OSTCExtensions.LinuxDiagnostic.1.manifest
-rw-r--r--   1 root root      3675 May  3 06:27 Microsoft.OSTCExtensions.LinuxDiagnostic.1.manifest.xml
drwxr-xr-x  11 root root      4096 Jul 29 14:37 Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029
-rw-r--r--.  1 root root      2639 Jan 27  2017 Microsoft.OSTCExtensions.LinuxDiagnostic.2.manifest
-rw-r--r--   1 root root      3675 Aug  4 06:04 Microsoft.OSTCExtensions.LinuxDiagnostic.2.manifest.xml
-rw-r--r--   1 root root      2287 Aug  8  2017 Microsoft.OSTCExtensions.LinuxDiagnostic.4.manifest
-rw-r--r--.  1 root root      2287 Mar 21  2017 Microsoft.OSTCExtensions.LinuxDiagnostic.5.manifest
drwxr-xr-x   6 root root      4096 Feb 26 11:41 Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1
-rw-r--r--   1 root root      4702 May  3 06:27 Microsoft.OSTCExtensions.VMAccessForLinux.1.manifest.xml
-rw-r--r--   1 root root      4702 Aug  4 06:04 Microsoft.OSTCExtensions.VMAccessForLinux.2.manifest.xml
-rw-r--r--   1 root root      4351 Jul 26  2017 Microsoft.OSTCExtensions.VMAccessForLinux.3.manifest
-rw-r--r--.  1 root root      4000 Jan 27  2017 Microsoft.OSTCExtensions.VMAccessForLinux.4.manifest
-r--------.  1 root root      1402 Sep 20  2016 ovf-env.xml
-rw-r--r--   1 root root         2 Feb 26 11:36 partition
-rw-r--r--   1 root root        21 Feb 26 11:36 Prod.1.agentsManifest
-rw-r--r--   1 root root      2019 May  3 06:18 Prod.1.manifest.xml
-rw-r--r--   1 root root        28 May  3 08:18 Prod.2.agentsManifest
-rw-r--r--   1 root root      1560 Aug  4 05:47 Prod.2.manifest.xml
-rw-r--r--   1 root root        12 Jul 17 10:08 Protocol
-rw-r--r--.  1 root root        36 Feb 26 11:36 provisioned
-rw-r--r--   1 root root        13 Feb 26 11:36 published_hostname
-rw-r--r--.  1 root root      2810 Jul 17 10:08 SharedConfig.xml
-r--------.  1 root root      1107 Jul 17 10:08 TransportCert.pem
-r--------.  1 root root      1704 Jul 17 10:08 TransportPrivate.pem
-rw-r--r--   1 root root    915142 Jul  2 18:47 v2.2.26.zip
drwxr-xr-x   3 root root      4096 Feb 26 11:36 WALinuxAgent-2.2.20
drwxr-xr-x   3 root root      4096 May  3 08:18 WALinuxAgent-2.2.25
drwxr-xr-x   9 root root      4096 Jul  2 18:48 WALinuxAgent-2.2.26
-rw-r--r--   1 root root        13 Jul 17 10:08 WireServerEndpoint`

**Comment by hglkrijger** [comment]
@tvvignesh so we are making some progress. Unfortunately there are some ongoing issues with the OMS extension. At this point you have a couple options - if you do not need it, you could just uninstall it via CLI/portal, and see if that fixes your CPU issues. There is also a lower possibility that LinuxDiagnostic is involved, so same thing there.

If you _do_ need them, however, you could reach out to the owners of those extensions and see if they can help. They might be able to help you upgrade/downgrade to a more stable version. Let me know if I can help loop in the owners, if you go that route.

/cc @danielsollondon @boumenot

**Comment by hglkrijger** [comment]
We have only seen high CPU from extensions, so I am closing this under the umbrella for #1316 - cgroups limits will prevent this type of runaway behavior.
