### ISSUE TITLE
setting authorised_keys and password not working for VM created from Images

### ISSUE THREAD

**Issue by rahul1809** [Azure/WALinuxAgent#1350]
Hi there, 

I'm trying to create VM from an **Image** that has **cloud-init** in it. I'm facing multiple issues here.

- I tried setting username and password authentication but that is not setting password if the user is already existing in the Image.
- Secondly, I tried to copy my public key to authorised_keys of the VM being deployed through az CLI, I assigned --adminUsername as one of the existing user and provided the public key from default **~/.ssh/id_rsa.pub** and provided destination path for authorized_keys as **~/\<adminUsername\>/.ssh/authorised_keys** but the keys are being copied to root user's authorised_keys.

Also, while deploying the vm though Image we have to provide either admin username and password or ssh public key authentication, but it is meaningless to pass them if they don't work and ultimately you have to use cloud-init to initialise the following information.

Please, comment and correct me if  i'm doing any thing wrong here. I have tried all the permutation and combinations for deployment and initialising my VM from created Image az cli parameters and custom-data.

PS:

- I'm using az cli on Ubuntu Machine (azure-cli (2.0.46))
- I able to do the above two requirements through cloud-config passing it in --custom-data parameter
- cloud-init is required for doing some more customization in the VM.

Thanks in Advance.

**Comment by roiyz-msft** [comment]
@rahul1809, can you please provide more information
"..I tried setting username and password authentication but that is not setting password if the user is already existing in the Image..." 
--In what way are you trying to set the username/pwd? 


Secondly, I tried to copy my public key to authorised_keys of the VM being deployed through az CLI, I assigned --adminUsername as one of the existing user and provided the public key from default ~/.ssh/id_rsa.pub and provided destination path for authorized_keys as ~/<adminUsername>/.ssh/authorised_keys but the keys are being copied to root user's authorised_keys.
-- What command are you using to perform this?

**Comment by narrieta** [comment]
@jasonzio - seems to be an issue in provisioning, could you check this out? thanks

**Comment by jasonzio** [comment]
It appears that --ssh-dest-key-path is not actually functioning. A change to disable this capability was made some time back. An attempt to use this option today should result in an error message along the lines of `Destination path for SSH public keys is currently limited to its default value /home/[username]/.ssh/authorized_keys  due to a known issue in Linux provisioning agent.`

Changing the path isn't as simple as just dropping the keys in a different directory; the agent "knows" where the ssh keys are, and the altered path isn't plumbed all the way through the control plane from Compute resource provider to the configuration information seen by the agent.

Note that many users use the "Custom Script Extension" to do VM customization rather than using cloud-init. We recognize that's a workaround, but it is available to you.

You should find that cloud-init with customization works on Ubuntu 18.04 if you don't use --ssh-dest-key-path.
