### ISSUE TITLE
Opting out of cgroups enforcement

### ISSUE THREAD

**Issue by pivotalguru** [Azure/WALinuxAgent#1519]
The wiki has this to opt out of cgroups enforcement.

> If cgroups limits cause any issues, you can opt-out by updating the following config in /etc/waagent.conf:
> 
> CGroups.EnforceLimits=y

You set enforce limits to true to disable it?  That doesn't make sense.

Secondly, I've set it to both y and n but I still see activity from waagent.  I see lots of these messages:
WARNING ExtHandler CGroup Microsoft.Azure.Extensions.CustomScript: Crossed the Memory Threshold. Current Value: 33683439616 bytes, Threshold: 16919.0 megabytes

How do I disable this?  I'm on version 2.2.40.

**Comment by firemanxbr** [comment]
Hi @pivotalguru I believe you can check the latest update of our 'waagent.conf' here: https://github.com/Azure/WALinuxAgent/blob/develop/config/waagent.conf#L129 that have a better description regarding this flag of this configuration. To make sure 'y' == True/Yes and 'n' == False/No. The default config is 'n'. You can set both options because it is boolean, 'y' or 'n'. To disable it just flag as our default config it is showing: 'n'.

**Comment by pivotalguru** [comment]
Thanks.  So the wiki page is incorrect.  Can this get updated?

Enabled
> CGroups.EnforceLimits=y

Disabled
> CGroups.EnforceLimits=n

As it is right now, it looks like it says to set the value to y to disable it.

Under heavy load, I see this in /var/log/messages:
WARNING ExtHandler CGroup Microsoft.Azure.Extensions.CustomScript: Crossed the Memory Threshold. Current Value: 18487123968 bytes, Threshold: 16919.0 megabytes

Why would activity in the vm cause the agent to consume more memory?

**Comment by pivotalguru** [comment]
I also see this process consuming a lot of CPU during heavy load:
> python -u bin/WALinuxAgent-2.2.40-py2.7.egg -run-exthandlers

**Comment by firemanxbr** [comment]
Sorry, but the documentation it is right, as I mentioned to Disable you have to use 'n'. Just to make clear: 

To Enabled:
CGroups.EnforceLimits=y

To Disabled:
CGroups.EnforceLimits=n

I believe you don't know how it works. If you configure to Enable you are enforcing the limits, in this case, you want that the agent and your extensions have limited use of resources. If you DISABLE you are saying to the agent and your extensions that you don't care about resources. Regarding the log, it is only a warning that will keep you informed about the use of resources by the agent and your extensions. 

I hope to be clear right now. Don't have any error our missing documentation, if you know that this issue is clear right now you can close it.

**Comment by pivotalguru** [comment]
https://github.com/Azure/WALinuxAgent/wiki/CGroups-support

> If cgroups limits cause any issues, you can opt-out by updating the following config in /etc/waagent.conf:
> 
>  CGroups.EnforceLimits=y

It literally says to set the value to y to opt-out (disable).

**Comment by firemanxbr** [comment]
Sorry but you are interpreting wrong the concept and the phrase in this doc, don't have in any place wrote it as DISABLE. If you read again, with calm you will translate it from:

**If cgroups limits cause any issues, you can opt-out by updating the following config in /etc/waagent.conf:

CGroups.EnforceLimits=y**

If you are getting PROBLEMS when you are using cgroup limits your can disable it, because the default is 'n'. In that case you will ENABLE the "enforce limits" that are not "cgroup limits". I believe your confusing is that cgroup limits(pass throw the limits) is a feature and enforce limits is (make sure that have limits).

**Comment by pivotalguru** [comment]
Enable "enforce limits" to disable the cgroup limits. 

Maybe the configuration should be "CGroups.limits" to avoid this odd setting something to true to disable and false to enable.

**Comment by johncrim** [comment]
I can create another issue if needed, but the ability to opt out of cgroups enforcement really should be configurable at the ARM template level. For our VMs, cgroups enforcements prevents automatic VM setup from completing. I believe I can work around this with cloud-init (I'll try), but I certainly can't work around it with a custom script extension, b/c the cgroups enforcement is preventing extensions from running.

**Comment by narrieta** [comment]
@pivotalguru - I agree that the description in the wiki doesn't read well. I'll update it. To disable enforcement, set the value to 'n' (which is the current default).

Currently enforcement is disabled by default. We are using the Warnings you see in the log to gather data, but they only point out that a limit was exceed and there is no enforcement of the limit at all (unless EnforceLimits is set to 'y')

**Comment by narrieta** [comment]
@johncrim - Currently enforcement of cgroup limits is disabled by default. We are still working on the enforcement logic and we will indeed expose this flag in ARM when we are ready to enable this feature. 

We will enforce limits in collaboration with the authors of each extension. At this point we are not enforcing limits on any extension. Since Custom Script can execute arbitrary code we will not enforce limits on it.

**Comment by narrieta** [comment]
updated wiki... enforcing limits is experimental and is disabled by default
