### ISSUE TITLE
WAagent is not provisioning user when deploying VM from Azure Portal

### ISSUE THREAD

**Issue by dbcloudbin-dev** [Azure/WALinuxAgent#1590]
Hi,
We have tested to deploy from Azure Portal a standard 'OpenLogic:CentOS:7.6:7.6.20190708' setting up an arbitrary admin user and password from the VM provisioning form and it works OK (as expected, we are able to connect to the VM with that user and password successfully).

However, if we create a new image (programatically) based on the same Centos image with no changes and we repeat a deployment from Azure portal with that new image providing an admin user and password, it is not able to connect. Reviewing the created VM, in fact there are no errors in /var/log/waagent.log, but the specified user is not created in the VM. However if we go again to the portal and reset the password, then it works successfully.

Any ideas?

Additional data:
WAAgent version: 2.2.41
Image creation process (script):
az vm create -n $INSTANCE_NAME -g $AZURE_RESOURCE_GRP --image $IMAGE_NAME --os-disk-name ${INSTANCE_NAME}-${VERSION//\./-}-disk --admin-username $IMAGE_OS_USER --authentication-type password --admin-password $MYPASSWORD --use-unmanaged-disk
az vm stop -n $INSTANCE_NAME -g $AZURE_RESOURCE_GRP 
az vm deallocate -g $AZURE_RESOURCE_GRP -n $INSTANCE_NAME
az vm generalize -g $AZURE_RESOURCE_GRP -n $INSTANCE_NAME
az image create -g $AZURE_RESOURCE_GRP -n ${INSTANCE_NAME}-${VERSION//\./-} --source $INSTANCE_NAME

**Comment by anhvoms** [comment]
Before you stopping/deallocating the VM so that it can be captured for image creation, the step "sudo waagent -deprovision+user" need to be run from within the VM. In a typical image building process using a script you should put that step as the last action in the script.

If you build your image with Packer or Azure Image Builder this step can be skipped because that step will be added automatically. 

Reference:
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/capture-image

**Comment by vrdmr** [comment]
Thanks for the input @anhvoms.

>However, if we create a new image (programatically) based on the same Centos image with no changes and we repeat a deployment from Azure portal with that new image providing an admin user and password, it is not able to connect. Reviewing the created VM, in fact there are no errors in /var/log/waagent.log, but the specified user is not created in the VM.

This could be because as this is a captured image, the provisioning agent didn't create a new user, while provisioning this new image (and to force it, you might need to follow @anhvoms's advice on running the `sudo waagent -deprovision+user`. @anhvoms - correct my understanding if this is the case)


> However if we go again to the portal and reset the password, then it works successfully. 

The user creation during provisioning and post-provisioning are done using a different mechanism (using [VMAccess extension](https://github.com/Azure/azure-linux-extensions/blob/master/VMAccess/README.md)). It executes the `useradd` and `passwd` on the new user explicitly and thus it works.

Feel free to reopen the issue if you feel it did not solve your issue. Thanks.
