### ISSUE TITLE
[BUG] debian 9 package is outdated

### ISSUE THREAD

**Issue by MaxMelcher** [Azure/WALinuxAgent#1605]
**Describe the bug**
The debian 9 waagent package is outdated and stuck during installation with apt-get install.

* apt-get install waagent installs version 2.2.34 and is stuck during installation 

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Debian 9.5
 - WALinuxAgent version: 2.2.34

**Additional context**
I installed debian based on an ISO to prepare it for azure. 
The **apt-get install waagent** kills the ssh session because it stucks - ctrl+c does not work. 
If you reboot, ssh is stuck and the vm is basically dead if you execute the deprovision command.
Installing the latest version (2.2.42) manually works. 

Is there a process to update the debian package?

**Comment by pgombar** [comment]
Hi @MaxMelcher, the agent that gets installed using the distro's package manager is controlled by the distro owners. As in, it is their responsibility to update the packages in their repo. As you've said, debian still has 2.2.34 in its [repo](https://packages.debian.org/stable/allpackages?format=txt.gz).

The agent installed from the package repository is the daemon which in turn installs the more up-to-date extension handler. It is not uncommon for the daemon to be an older version of the agent. For more info about that, see [this FAQ](https://github.com/Azure/WALinuxAgent/wiki/FAQ#what-does-goal-state-agent-mean-in-waagent---version-output). So, the process to update the debian package is the owned by the distro owners.

As to why your installation got stuck, we're unable to tell without more info. I tried `apt-get install waagent` on a Debian 9 VM and 2.2.34 was successfully installed.

If you need more help with installing 2.2.34 from source, feel free to re-open this issue. I'm closing it as it seems like the main point of the issue was the outdated Debian package and how to update it.
