### ISSUE TITLE
Agent deletes keys that it then does not regenerate

### ISSUE THREAD

**Issue by colemickens** [Azure/WALinuxAgent#162]
https://github.com/Azure/WALinuxAgent/blob/52ece05e6b925fa6e820b458a40f1d302647a4f8/waagent#L6410

Note that it will delete all existing keys, even though it only regenerates a certain type. It's causing ssh host key regeneration issues on NixOS.

It should be more selective about what it deletes.

**Comment by ahmetalpbalkan** [comment]
@colemickens I think it makes sense to delete them all as they may be leftovers from a captured image.

I believe it is possible to specify the key type to be generated in `Provisioning.SshHostKeyPairType`. Does specifying that work for NixOS?

**Comment by colemickens** [comment]
The NixOS guy fixed this a while back, I don't remember exactly how. I think if you just don't have the agent manage ssh keys that you avoid this problem.

IMO, the generalization process should delete these keys then... not the agent on a fresh boot after generalization.

**Comment by ahmetalpbalkan** [comment]
valid point. @szarkos  do you remember why the agent is in the business of deleting the existing SSH Host Keys in the first place.

The generalization step (i.e.`waagent -deprovision`) should be deleting these host keys and then users can use `Provisioning.SshHostKeyPairType` the type of the key to generate via the agent.

**Comment by szarkos** [comment]
It's old functionality, but probably there for safety.  In some distros it's easy to accidentally regenerate the keys, i.e. if they reboot for some reason before capturing the VM.  I've certainly done that before.

By default the agent thinks that it is solely responsible for generating the host keys, and so in the general case I think it makes sense to remove the previous host keys first.  We have the RegenerateSshHostKeyPair configuration to override this functionality.  The bug here is that the agent only generates rsa keys, but adding dsa and ecdsa should be trivial.  That may then make the Provisioning.SshHostKeyPairType parameter obsolete.

**Comment by ahmetalpbalkan** [comment]
@szarkos that makes sense. In the rewrite of the provisioning part (that never landed), I was basically generating all types of keys I could. That's a sensible option.

Out of curiosity, under what circumstance(s) which program(s) would regenerate ssh host keys?

**Comment by szarkos** [comment]
For example - on RHEL/CentOS/* the host keys will be generated when the SSH service is started.

Debian has this startup script called generate-ssh-hostkeys that is installed on most cloud images, but not all (I think it was removed from GCE because their agent handles this).  It's difficult for the agent to know when/if it is solely responsible for managing the host keys, so best to assume that it should unless configured otherwise.

**Comment by ahmetalpbalkan** [comment]
@szarkos I see, thanks. In this case, it is best to keep this as wontfix.
