### ISSUE TITLE
[BUG]The extension uninstalled log annoys customer

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#1624]
**Describe the bug**
It's a customer issue: https://bugzilla.redhat.com/show_bug.cgi?id=1746180
After extension is uninstalled(e.g. LinuxDiagnostics), everytime the waagent service restart there is a log like below, which annoys the customer:
2019/08/28 19:06:52.805484 INFO [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.123] Target handler state: uninstall
2019/08/28 19:06:52.809506 INFO [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.123] [Uninstall] current handler state is: notinstalled
The customer misunderstood this log that they thought the WALA was not installed or working. Actually I think this log is not useful for customers because the Extension is removed for a long time. Shell we consider to remove this log? Thanks!

**Distro and WALinuxAgent details (please complete the following information):**
WALinuxAgent-2.2.38 running on redhat 7.7
Python: 2.7.5
Goal state agent: 2.2.42

**Comment by larohra** [comment]
The above mentioned scenario only happens if there is no new extension related action (goalstate) on the VM and you restart the agent. When you restart the agent, it re-runs the last settings that it received and logs accordingly (hence the multiple Uninstall calls). If you dont restart the agent, then you wont see any new Uninstall logs.

If you do a new extension related activity (like running RunCommand, or resetting password, etc) on the VM, the uninstall line would disappear and would only log the relevant data.
