### ISSUE TITLE
[2.1] "--init-system" gets ignored completely

### ISSUE THREAD

**Issue by z3ntu** [Azure/WALinuxAgent#177]
It is called "deprecated" (not removed completely), but still completely ignored.

**Comment by ahmetalpbalkan** [comment]
@z3ntu sorry for the inactivity here. It indeed looks like 2.1 branch totally ignores the `--init-system` input. I agree that it could've been changed better by failing instead of just printing a warning saying it is deprecated and ignoring it.

Do `--lnx-distro-*` arguments do the same job for you?

**Comment by z3ntu** [comment]
I believe yes (it's some that I did something with WALinuxAgent)

**Comment by ahmetalpbalkan** [comment]
Okay, in this case keeping the issue open. We should either remove this flag completely or fail instead of ignoring the input.
