### ISSUE TITLE
[2.1] remove bin/ folder (long-term goal)

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/WALinuxAgent#223]
bin/ directory has a copy of `waagent2.0` (2.0.16).

I don't know why this is the case, but that should not be present there.

@szarkos any ideas?

**Comment by brendandixon** [comment]
@ahmetalpbalkan I believe it was historical. We should remove it unless it's present for an unnamed dependency (e.g., an extension).

**Comment by szarkos** [comment]
Yeah, I believe some extensions import waagent as a python lib.

**Comment by brendandixon** [comment]
@ahmetalpbalkan @szarkos Can we get that changed?

**Comment by szarkos** [comment]
It would probably require updates to VMAccess, CustomScript and I think parts of the diagnostics extension and VMBackup I think, maybe others.

**Comment by ahmetalpbalkan** [comment]
just did a grep on `waagent` in the azure-linux-extensions repo and there's _massive_ dependencies taken on waagent, for:

- simple file read/write operations
- logging functions and levels
- command invocation
- telemetry (through event sink –– 💀 ⚠️  extensions probably should not be using telemetry channel directly?)
- distro identification
- discovery of /var/lib/waagent path (⚠️  same can be done by figuring out the basename of argv[0] and just doing `../..`, like docker-extension does)
- `/etc/waagent.conf` parser ( ⚠️  I don't know why any extension would need this, apparently to read Http proxy setting)
- restarting ssh service
- ...

**Comment by brendandixon** [comment]
@ahmetalpbalkan @szarkos Ok. I suggest we file issues against every offending extension to get these fixed. A quick fix in each case just imports the code they require. Proper fixes would do better.

**Comment by szarkos** [comment]
The actual code used from the agent is probably pretty small.  However it makes sense to maintain some sort of shared library to handle distro-specific actions rather than maintain distro detection and classed separately in each extension.  The agent works here since most of the extensions are also written in Python and waagent must be there since it's the only thing that can handle vm extensions at the moment.

For example, the VMAccess extension might need to create a user, but the mechanism for this will vary between distros.  In theory even a very custom distro could come along, fork the agent with their own distro class and it would work with VMAccess without changing the extension itself.

**Comment by brendandixon** [comment]
@szarkos I wholly agree with sharing code. But such is best accomplished via installed packages vs. assumptions. I suggest, then, we identify the shared parts and move them into a package upon which the various extensions depend. Let's make it official vs. ad hoc.

**Comment by ahmetalpbalkan** [comment]
Closing this as not actively an issue.
