### ISSUE TITLE
[BUG] Canonical 0001-com-ubuntu-server-hirsute 21_04 21.04.202105111 see error message in waagent.log

### ISSUE THREAD

**Issue by LiliDeng** [Azure/WALinuxAgent#2254]
**Describe the bug: A clear and concise description of what the bug is.**
Provision VM using image Canonical 0001-com-ubuntu-server-hirsute 21_04 21.04.202105111
See below error log in waagent.log.
ERROR ExtHandler Command: [iptables -w -t security -L OUTPUT --zero OUTPUT -nxv], return code: [4], result: [iptables v1.8.7 (nf_tables):  CHAIN_ZERO failed (No such file or directory): chain OUTPUT

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: [e.g. Ubuntu 21.04]
 - WALinuxAgent version 
 WALinuxAgent-2.2.46 running on ubuntu 21.04
 Python: 3.9.4
 Goal state agent: 2.2.54.2

**Additional context**
Please help understand the impact of this error message.

**Log file attached**
[waagent.log](https://github.com/Azure/WALinuxAgent/files/6505562/waagent.log)

**Comment by narrieta** [comment]
@LiliDeng - You can ignore that message, it is totally harmless. The agent is trying to collect some debugging information that is no longer needed; we will remove this code in our next release.

**Comment by LiliDeng** [comment]
thanks @narrieta

**Comment by narrieta** [comment]
@LiliDeng Actually, it turns out some of that debugging info is still useful.

The error message can be ignored; this info is collected periodically and in your VM only the first call failed and subsequent calls succeeded.

In the current agent this message is no longer an error, but just a warning: https://github.com/Azure/WALinuxAgent/blob/develop/azurelinuxagent/common/osutil/default.py#L178

Ubuntu is still using version 2.2.46 in their images; once the agent is updated this would show up as a warning.
