### ISSUE TITLE
[BUG] WAAgent fills disk with log entries - error: "NameError: name 'get_python_cmd' is not defined"

### ISSUE THREAD

**Issue by capncodewash** [Azure/WALinuxAgent#2336]
On multiple Azure Linux VMs, the boot drives fill up to the point where the machine is unusable, because of the /var/log/waagent.log file becoming absolutely massive (~15GB on one machine). It seems that it cannot find a Python module, and re-attempts to run a process continuously.

**Distro and WALinuxAgent details**
WALinuxAgent-2.3.1.1 running on centos 8.4.2105
Python: 3.6.8
Goal state agent: 2.3.1.1

**Additional context**
This started happening on two machine over the past few days. The two machines where I've seen this fail to respond, because their disks are full. Reinstalling the package has no effect.

The only solutions seem to be to delete the huge log file, and either disable or remove WALinuxAgent.

The machines have other versions of Python installed at `/opt/python/VERSION`, e.g.:

```
$ ls /opt/python/
3.6.12  3.7.10  3.8.8  3.9.4  miniconda  miniconda.sh
```
But these versions have been present for some time, and shouldn't cause a conflict. The default version of Python on the PATH is:

```
/opt/python/3.9.4/bin/python
```

**Log file entries**
The log file at /var/log/waagent.log is full of hundreds of thousands of entries similar to the one below:

```
2021-08-23T08:00:21.856964Z INFO Daemon Daemon Installed Agent WALinuxAgent-2.3.1.1 is the most current agent
2021-08-23T08:00:21.857200Z WARNING Daemon Daemon Agent WALinuxAgent-2.3.1.1 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' failed with exception: name 'get_python_cmd' is not defined
2021-08-23T08:00:21.857406Z ERROR Daemon Daemon Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.3.1.1 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' failed with exception: name 'get_python_cmd' is not defined Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/azurelinuxagent/ga/update.py", line 156, in run_latest
    cmds[0] = get_python_cmd()
NameError: name 'get_python_cmd' is not defined
```

I'd be grateful for any assistance.

**Comment by narrieta** [comment]
@capncodewash what is the image you are using? thanks

**Comment by narrieta** [comment]
@capncodewash could you also paste the output of 

waagent --version

thanks

**Comment by pfernie** [comment]
We have seen the same behavior on a Centos 8.4. Downgrading from `2.3.1.1` to a prior version (2.2.49.2) via `dnf` solves the issue. In our case, the package is installed from the `openlogic` repo.
```
WALinuxAgent.noarch                       2.3.1.1-1_ol001.el8                   openlogic
```

As shown via `waagent --version`, the goal state agent successfully runs at version `2.3.1.1`, although the package itself is `2.2.49.2`.

```
# waagent --version
WALinuxAgent-2.2.49.2 running on centos 8.4.2105
Python: 3.6.8
Goal state agent: 2.3.1.1
```

And from `waagent.log`:
```
2021-08-23T14:46:25.738137Z INFO Daemon Daemon Agent WALinuxAgent-2.3.1.1 launched with command '/usr/bin/python3.6 -u bin/WALinuxAgent-2.3.1.1-py2.7.egg -run-exthandlers' is successfully running
```

Upgrading the `WALinuxAgent` package via `dnf` to `2.3.1.1` re-introduces the behavior described in this issue.

**Comment by narrieta** [comment]
There may be something wrong with those packages.

@capncodewash - on 2.2.49.2 there is indeed a call to get_python_cmd() on update.py at [line 156](https://github.com/Azure/WALinuxAgent/blob/v2.2.49.2/azurelinuxagent/ga/update.py#L156), but the function is defined earlier on the same file, at [line 85](https://github.com/Azure/WALinuxAgent/blob/v2.2.49.2/azurelinuxagent/ga/update.py#85).

could you check the contents of /usr/lib/python3.6/site-packages/azurelinuxagent/ga/update.py?

@pfernie - on 2.3.1.1 the call to get_python_cmd() has been removed, so that error should not be there https://github.com/Azure/WALinuxAgent/blob/v2.3.1.1/azurelinuxagent/ga/update.py#L157

**Comment by pfernie** [comment]
@narrieta Thanks, I think you are correct; this seems like a mis-package. The `2.3.1.1` package available from `openlogic` repo is located [here](http://olcentgbl.trafficmanager.net/openlogic/8/openlogic/x86_64/) Examining the contents of that `rpm` reflect a `update.py` that looks to be a badly patched version; it refers to `get_python_cmd()` but lacks a definition for it:
```
site-packages/azurelinuxagent/ga via 🐍 v3.9.6
❯ rg get_python_cmd update.py                                             21-08-23 15:43
156:            cmds[0] = get_python_cmd()
```

On investigation, on our setup that repo is only providing these spurious packages; downgrading the package to `2.2.49.2` and disabling the repo has corrected the problem here; hopefully that is useful to @capncodewash as well.

**Comment by narrieta** [comment]
Thank you @pfernie... not sure if there is a way to submit feedback in that repo,,, they may want to fix it.

**Comment by capncodewash** [comment]
Thank you very much @narrieta and @pfernie for looking into this.

I've reported it as a bug to the CentOS project here:
https://bugs.centos.org/view.php?id=18287

In the meantime, since I don't really use the package, I've just stopped and disabled the services. Hopefully the CentOS team will update the package.

I'll close this issue.
