### ISSUE TITLE
How to disable Azure Portal to automatically install OmsAgentForLinux on my VM?

### ISSUE THREAD

**Issue by zshu11** [Azure/WALinuxAgent#2958]
Hi, Guys:

Since my device is security device, and not allow download extension from outside,
I find that after some time, Azure portal automatically install OmsAgentForLinux extension
on my LinuxVM.
1): How to disable Azure Portal to automatically install OmsAgentForLinux on my VM?
2): when deploy a VM on Azure Portal, which setting will disable  Azure Portal to automatically install OmsAgentForLinux on my VM?

Thanks.

**Comment by narrieta** [comment]
@zshu11 I see that you already reported this in https://github.com/microsoft/OMS-Agent-for-Linux/issues/1548. That is the proper repo for this issue. 

As a note, some organization use Azure Policy to deploy extensions automatically. You may want to check if this is your case. Otherwise, please follow up in the OMS repo.

**Comment by zshu11** [comment]
Thanks. Narrieta.
