### ISSUE TITLE
[2.1.3/2.1.5] CustomScript fails to report status

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/WALinuxAgent#323]
It appears like when CustomScriptExtension fails on Ubuntu 16.04 (has agent v2.1.3 but this behavior reproes on agent v2.1.5 as well), the status does not get propagated to Azure Portal/API ever:

![image](https://cloud.githubusercontent.com/assets/159209/16821385/dbff373e-490a-11e6-8a74-0520ca8325a0.png)

The command to repro the error:

    azure vm extension set <GROUP> <VM> CustomScriptForLinux Microsoft.OSTCExtensions '1.5' --public-config '{}'

this causes an error because public config is missing a required field.

So far what I manually verified is:

- Ubuntu14.04 (agent v2.0.14) works just fine and failure reported just fine to the API.
- Ubuntu16.04 stock image (agent v2.1.3) does not work
- Ubuntu16.04 stock image with updated agent (v2.1.5-develop) does not work
- `.status` files reported on 14.04 is [here][1] and 16.04 is [here][2]. (I can't spot a difference, ordering of fields is probably because I used jq to indent)
- Status gets propagated to the portal/API ([screenshot][3]) if extension succeeds.

[1]: https://gist.github.com/anonymous/d31ba60a99752eb895f8b5a9f0e506e2
[2]: https://gist.github.com/anonymous/21ef5025f1525d7b3635c1f13ceccabc
[3]: https://cl.ly/1k1J0r1n251U/Image%202016-07-13%20at%203.10.48%20PM.png

This suggests that something broken in 2.1.x agents regarding reporting the failure status.

@boumenot have you observed this before?
@hglkrijger do you know if the failure case is covered by the BVT tests?
@brendandixon any ideas?

**Comment by ahmetalpbalkan** [comment]
Another finding:

Another extension such as DockerExtension reports failure just fine on 2.1.x. Repro:

    azure vm extension set <GROUP> <VM> DockerExtension Microsoft.Azure.Extensions '1.1' --public-config '{"docker":{"port":-1}}'

> ![image](https://cloud.githubusercontent.com/assets/159209/16821868/9c263722-490d-11e6-8652-e453447419bd.png)

I can reproduce this currently on CustomScriptExtension and haven't checked beyond that. Since `.status` files are the same, I am thinking this is a WALA issue.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Nothing jumps out. However, it is odd that it works for one extension and not another. That suggests, at some level, an interaction between the agent and the extension causing the issue.

**Comment by ahmetalpbalkan** [comment]
OK more info, I enabled verbose logging at waagent. Here is the status report line:

```
2016/07/13 22:33:36.768872 VERBOSE Blob type=BlockBlob
2016/07/13 22:33:36.776179 VERBOSE Upload block blob
2016/07/13 22:33:36.782849 VERBOSE HTTP Req: PUT https://vhdsj23ca8qpyh731sgjcrqo.blob.core.windows.net/vhd-ub16sa/ub16sa.7884a77d-a01e-4ce7-a146-50d780e62aa5.status?sv=2014-02-14&sr=b&sig=MgAlnLXN4%2FKcb4uXcfoyCpi2l5x4nburamBC6WvEgGY%3D&se=9999-01-01T00%3A00%3A00Z&sp=rw
2016/07/13 22:33:36.812285 VERBOSE     Data={"version": "1.0", "aggregateStatus": {"handlerAggregateStatus": [{"handlerName": "Microsoft.OSTCExtensions.CustomScriptForLinux", "status": "NotReady", "handlerVersion": "1.5.2.0", "code": -1, "formattedMessage": {"message": "(000003)Invalid status/status: failed", "lang": "en-US"}}], "guestAgentStatus": {"version": "2.1.5.rc7", "status": "Ready", "formattedMessage": {"message": "Guest Agent is running", "lang": "en-US"}}}, "timestampUTC": "2016-07-13T22:33:36Z"}
2016/07/13 22:33:36.868100 VERBOSE     Header={'Content-Length': '468', 'x-ms-blob-type': 'BlockBlob', 'x-ms-date': '2016-07-13T22:33:36Z', 'x-ms-version': '2014-02-14'}
2016/07/13 22:33:36.905251 VERBOSE HTTP Resp: Status=201
2016/07/13 22:33:36.912365 VERBOSE     Header=[('Transfer-Encoding', 'chunked'), ('Content-MD5', '+0Fwc5+TzOv/Gz63CDYh3w=='), ('Last-Modified', 'Wed, 13 Jul 2016 22:33:36 GMT'), ('ETag', '"0x8D3AB6DBB128061"'), ('Server', 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'), ('x-ms-request-id', '967af60c-0001-0088-0f56-dd864f000000'), ('x-ms-version', '2014-02-14'), ('Date', 'Wed, 13 Jul 2016 22:33:35 GMT')]
2016/07/13 22:33:36.954727 VERBOSE Uploading status blob succeeded
```

##  Indented (what waagent uploads to .status blob):

```json
{
  "version": "1.0",
  "aggregateStatus": {
    "handlerAggregateStatus": [
      {
        "handlerName": "Microsoft.OSTCExtensions.CustomScriptForLinux",
        "status": "NotReady",
        "handlerVersion": "1.5.2.0",
        "code": -1,
        "formattedMessage": {
          "message": "(000003)Invalid status/status: failed",
          "lang": "en-US"
        }
      }
    ],
    "guestAgentStatus": {
      "version": "2.1.5.rc7",
      "status": "Ready",
      "formattedMessage": {
        "message": "Guest Agent is running",
        "lang": "en-US"
      }
    }
  },
  "timestampUTC": "2016-07-13T22:33:36Z"
}
```

## 0.status file of the extension

```
# cat 0.status | jq .
[
  {
    "status": {
      "status": "failed",
      "formattedMessage": {
        "lang": "en-US",
        "message": "Enable failed: Failed with error: CommandToExecute is empty or invalid, Traceback (most recent call last):\n  File \"/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0/customscript.py\", line 79, in main\n    enable(hutil)\n  File \"/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0/customscript.py\", line 113, in enable\n    start_daemon(hutil)\n  File \"/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.0/customscript.py\", line 263, in start_daemon\n    raise ValueError(error_msg)\nValueError: CommandToExecute is empty or invalid\n"
      },
      "operation": "Enable",
      "code": "0",
      "name": "Microsoft.OSTCExtensions.CustomScriptForLinux"
    },
    "version": "1.0",
    "timestampUTC": "2016-07-13T22:30:34Z"
  }
]
```

See that `"status":"failed"` is converted into `"status":"NotReady"` in uploaded blob. And the `formattedMessage` does not show up in the portal either.

**Comment by ahmetalpbalkan** [comment]
In Docker Extension case, when it fails, here is what's uploaded (:warning: pay attention: `"status": "Ready"`):

```json
{
  "version": "1.0",
  "aggregateStatus": {
    "handlerAggregateStatus": [
      {
        "formattedMessage": {
          "message": "Plugin enabled",
          "lang": "en-US"
        },
        "handlerName": "Microsoft.Azure.Extensions.DockerExtension",
        "status": "Ready",
        "handlerVersion": "1.1.1606092330",
        "code": 0,
        "runtimeSettingsStatus": {
          "sequenceNumber": 0,
          "settingsStatus": {
            "version": 1,
            "status": {
              "configurationAppliedTime": null,
              "formattedMessage": {
                "message": "Enable Docker failed: ERROR: error parsing handler settings: error deserializing public settings for handler: json: cannot unmarshal number into Go value of type string",
                "lang": "en-US"
              },
              "operation": "Enable Docker",
              "status": "error",
              "name": "Microsoft.Azure.Extensions.DockerExtension",
              "code": 0
            },
            "timestampUTC": "2016-07-13T22:38:32Z"
          }
        }
      }
    ],
    "guestAgentStatus": {
      "version": "2.1.5.rc7",
      "status": "Ready",
      "formattedMessage": {
        "message": "Guest Agent is running",
        "lang": "en-US"
      }
    }
  },
  "timestampUTC": "2016-07-13T22:38:32Z"
}
```

**Comment by brendandixon** [comment]
@ahmetalpbalkan And...your point is? The CustomScriptExtension failed. That's clear. What term is to be used to report failure? What term did the 2.0.x agent use? Etc. It does not seem correct to report "Ready", but perhaps the "failure" term is also incorrect?

**Comment by ahmetalpbalkan** [comment]
@brendandixon I'm not sure about the terminology. You're probably more familiar with extensions spec. But this Ready/NotReady thing appears to be something the agent sets; not the extension handler. I just found an issue, and reported it.

**Comment by brendandixon** [comment]
@ahmetalpbalkan @hglkrijger First, the specification limits the values of the `status:status` field, that extensions write to `#.status`, to `transitioning`, `error`, `success`, or `warning`.

Confusingly, and with little guidance, the specification then limits the `handlerAggregateStatus:status` field of the `AggregateStatus` blob to `Installing`, `NotReady`, `Ready`, and `Unresponsive`.

My interpretation suggests that mapping `failed` to `NotReady` is correct.

However, with custom script it's a bit more complex since the specification draws no distinction between the extension itself failing and work the extension was asked to perform (e.g., run a script) failing.

Do we have the `#.status` files the CustomScript extension creates?

**Comment by brendandixon** [comment]
@ahmetalpbalkan @hglkrijger I've dug a bit more.

Extension status from `#.status` is *not* translated; it is injected into the aggregate status blob under `handlerAggregateStatus:runtimeSettingsStatus:settingsStatus:status`.

It turns out that processing between 2.0.x and 2.1.x changed significantly in this area.

The 2.0.x branch only monitors the presence of a `HandlerState` file the agent writes within the extension's config directory. That file contains a single line denoting the extension's state (e.g., "Enabled"). It then maps that value to the reported status using constant map (e.g., "Enabled" maps to "Ready"). It sets this file / state to "Enabled" if *it seems* the enable command complete successfully.

The 2.1.x branch, on the other hand, is, in a sense, cleaner, but different. First, it collects the state under a `handler_state` directory within `/var/lib/waagent`. The state of each handler / extension is written a handler / extension specific directory. It records, as separate files, the actual state (e.g., "Enabled") and the resulting status (e.g., "Ready"). (This strategy is slightly risky since "Ready" should equate to "Enabled". Any errors encountered writing the state will cause the status to be incorrect.) More importantly, the calls to `launchCommand` are now wrapped, by `handle_ext_handler` in a `try: xxx except:` handler that forcibly sets the status to "NotReady" if an exception occurs *at any time and for any command.* This seems aggressive and likely explains the difference in behavior. Worse, the 2.1.x branch converts a non-zero return code from the enable command (that is, if subprocess.Popen returns non-zero), it raises an exception that is then caught by the `handler_ext_handler` that then marks the extension "NotReady." I believe this difference explains the behavior (since it appears from the files above that the CustomScript extension return -1?). The 2.0.x branch, in this case, simply logged an error.

I believe we should remove converting a non-zero return code to an exception. Exceptions are dangerous things unless the model within the code for handling them is clear. That model is not at all clear in this code.

**Comment by ahmetalpbalkan** [comment]
I have not tried if this is fixed. If so, feel free to close. @boumenot any ideas if this is the same issue with VMAccess (https://github.com/Azure/azure-linux-extensions/issues/208)?

**Comment by hglkrijger** [comment]
I think for now we have agreed that the extension state api is somewhat unclear in this case. I am closing the agent issue until such time as installation data requires us to address it in depth.
