### ISSUE TITLE
CentOS 6.5 VM hangs with WAAgent error

### ISSUE THREAD

**Issue by ravisha22** [Azure/WALinuxAgent#343]
I'm seeing the error in the below image in my CentOS 6.5 VM with WAAgent installed and latest LIS. The VM when moved to Azure works just fine, but when I move back to VMM environment using ASR, it starts hanging with this errors.
Any pointers?
![whatsapp-image-20160728](https://cloud.githubusercontent.com/assets/20698614/17205296/e11036d2-54dc-11e6-99cd-b9fc008a0cb2.jpeg)

P.S: I'm not a Linux guy!

**Comment by brendandixon** [comment]
@ravisha22 I'm sorry: What is ASR?

The agent expects to be running within Azure and probing for the wireserver. Those calls are failing, which causes the agent to fail.

**Comment by ravisha22** [comment]
Hi Brendondixon, I figured out as much myself, I'm looking for a why. Also just want to make sure this IS Azure repo discussion because ASR is site recovery.

**Comment by hglkrijger** [comment]
> The VM when moved to Azure works just fine, but when I move back to VMM environment using ASR, it starts hanging with this errors.

@ravisha22, which vmm environment are you referring to? We support initial provisioning to SCVMM, but as far as I am aware we do not support moving between environments in that way (though I could be wrong). If the screenshot references a SCVMM environment, then the reason you see failures is because the script which indicates an SCVMM environment is not found. Is this script present on the attached cdrom?

If so, we have recently made some fixes in this area. If you feel there is a bug, please test against 2.1.5 and let us know what you find. 

https://github.com/Azure/WALinuxAgent/releases/tag/v2.1.5
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-update-agent/

**Comment by ravisha22** [comment]
Hi @hglkrijger we are using Azure site recovery to failover/move the VM from VMM environment in on-premises to Azure and back for DIsaster recovery operation. The agent installed is the latest version from GitHub repository. The VMM script referenced in the error is not loaded automatically in the CD-ROM drive and  the help file has no mention of it. Anyway to file this issue as a bug?

**Comment by hglkrijger** [comment]
>move the VM from VMM environment in on-premises to Azure and back 

@ravisha22, which vmm environment?

**Comment by hglkrijger** [comment]
@ravisha22, I will go ahead and close this. If you are still seeing an issue please reopen and let us know which vmm environment you are using.
