### ISSUE TITLE
[2.2] Fingerprint element value in ovf-env.xml should be auto-converted to uppercase when parsed

### ISSUE THREAD

**Issue by hosungsmsft** [Azure/WALinuxAgent#522]
To support customers who are used to waagent 2.0 behavior (which by default auto-converts the Fingerprint value to uppercase).

**Comment by hglkrijger** [comment]
@hosungsmsft we discussed this and although it is true that 2.0.x had this behavior, 2.1.x changed it quite some time ago (>1 year now). I know at least one customer was affected by this, however if we change it back we may be affecting even more customers who have taken a dependency on the current behavior. In addition, keeping the case unchanged seems like the expected behavior. I am closing this for now, but we can always reopen if necessary.
