### ISSUE TITLE
Update of Agent kills custom script

### ISSUE THREAD

**Issue by libby2cm** [Azure/WALinuxAgent#582]
I have an automated routine which deploys UBU 16.04LTS VM's and as part of that, it runs the custom script extension with a customization script I provide.  The first part of this script does an update of all packages on the VM, and I have noticed that when it tries to update the walinuxagent package, my provisioning script terminates.. presumably because the agent terminates while being upgraded, so the script running in flight thus dies.

Is there a way this package can be altered so that it will not terminate a running script extension on update?

**Comment by brendandixon** [comment]
@libby2cm Updating all packages via a script under agent control can cause the problem described. The package system does not "know" that the agent (via an extension) initiated the update and, so, terminates / restarts the agent.

In general, I don't recommend updating *all* packages are part of deploying a VM. That can lead to unexpected behavior in other ways (e.g., if code depended on package behavior that now varies). It is better to create an updated image out-of-band and deploy it.

I hope this helps!

**Comment by szarkos** [comment]
One way to handle this is to hold the 'walinuxagent' package - "apt-mark hold walinuxagent".  You can then use "apt-mark unhold walinuxagent" at the end of the script.

Another option is to switch to using cloud-init in Ubuntu rather than customscript.  You can send a cloud config like the following via customdata:

  #cloud-config
  apt_upgrade: true

See also this doc for more info: https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-using-cloud-init
