### ISSUE TITLE
[2.2.10] If there're 2 DNS servers, wala doesn't get endpoint correctly

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#680]
Hi there,

When we set 2 DNS servers in a vnet, the dhcp lease is like this:
lease {
...
  option domain-name-servers 10.16.0.141,10.16.0.142;
...
}

WALA cannot separate the 2 addresses, and print error logs:
```
2017/04/25 06:51:48.075192 INFO Test for route to 168.63.129.16
2017/04/25 06:51:48.081849 WARNING No route exists to 168.63.129.16
2017/04/25 06:51:48.088245 INFO Checking for dhcp lease cache
2017/04/25 06:51:48.094441 INFO looking for leases in path [/var/lib/dhclient/dhclient-*.lease]
2017/04/25 06:51:48.108140 INFO dhcp entry:10.16.0.141,10.16.0.142, 245:True, expired:False
2017/04/25 06:51:48.117049 INFO found endpoint [10.16.0.141,10.16.0.142]
2017/04/25 06:51:48.123686 INFO cached endpoint found [10.16.0.141,10.16.0.142]
2017/04/25 06:51:48.131633 INFO Cache exists [True]
2017/04/25 06:51:48.136811 INFO Wire server endpoint:10.16.0.141,10.16.0.142
2017/04/25 06:53:48.267302 INFO WireServer is not responding. Reset endpoint
2017/04/25 06:53:48.276484 INFO Protocol endpoint not found: WireProtocol, [000008] [000009] HTTP GET failed
2017/04/25 06:53:48.296355 INFO Protocol endpoint not found: MetadataProtocol, [000008] 400 - GET: http://169.254.169.254/Microsoft.Compute/identity?api-version=2015-05-01-preview&$expand=*
```

I don't know in which scenario there's no 168.63.129.16 route, so I have to remove this route manually to reproduce it. But it does exist in one of our customer's VM. Could you please have a look? Thanks!

My reproduce steps:
1. Create a VNet, set 2 DNS servers in it.
2. Create a RHEL-7.2 VM in ASM mode with this VNet.
3. Access to the VM, run "route del -host 168.63.129.16"
4. service waagent restart

**Comment by brendandixon** [comment]
@yuxisun1217 First, the route to 168.63.129.16 should *not* be removed. That is the default wireserver route for all VMs running within a VNet (e.g., any VM launched via CRP).

Second, when not in a VNet and not provided, the agent relies on DHCP option 245 to obtain it. How it retrieves that is distribution dependent. On RedHat (see `azurelinuxagent/common/osutil/redhat.py`) the agent assumes it can obtain this from the DHCP leases cached in either `/var/lib/dhclient/dhclient-*.lease` or, for Network Manager VMs, `/var/lib/NetworkManager/dhclient-*.lease`. In both cases, the agent "globs" and scans the files one containing option 245 and uses it (see `azurelinuxagent/common/osutil/default.py#get_endpoint_from_leases_path`).

I suppose the agent could be more complex, but, at present, the behavior is By Design in that we've not engineered the agent to be more discriminating. If this is a common case (very doubtful), we could re-evaluate.

I hope this helps!

**Comment by yuxisun1217** [comment]
Thanks @brendandixon . We'll try to dig more about why it's occurred in customer VM. I'll update here if there're something new.

**Comment by yuxisun1217** [comment]
Hi @brendandixon , we think more about this and check log again. In customer VM, the eth0 is not up at that time, so that the route table is empty, and WALA cannot get 168.63.129.16 from route table. This might be the reason why it use DNS as endpoint server address.

**Comment by brendandixon** [comment]
@yuxisun1217 Well, if `eth0` (or whatever is the primary interface) is down, then the agent will not function. Nor will much else. I don't believe we have an agent problem.
