### ISSUE TITLE
waagent not closing connection to terminal when daemonizing

### ISSUE THREAD

**Issue by rjschwei** [Azure/WALinuxAgent#70]
When starting waagent from console, ssh or alike I noticed that it doesn't close the file descriptors for the console.

As a result, detaching from console (e.g. logging out from the ssh connection) doesn't work. Or when running from the yast2 runlevel editor, yast2 would just hang.

Inspecting the list of still open file descriptors after launch:

borg-3:~ # ps auxf | grep waagent
root     55911  0.0  0.0   5720   840 pts/1    S+   12:26   0:00          \_ grep waagent
root     55759  0.1  1.7  73528 15036 pts/0    S    12:24   0:00 /usr/bin/python /usr/sbin/waagent -daemon

borg-3:~ # find /proc/55759/fd*
/proc/55759/fd
/proc/55759/fd/0
/proc/55759/fd/1
/proc/55759/fd/2
/proc/55759/fdinfo
/proc/55759/fdinfo/0
/proc/55759/fdinfo/1
/proc/55759/fdinfo/2

This is a problem that had been seen and fixed in several other services when starting from sysv init. One fix is to close fd 0-2 when daemonizing.

SUSE bugzilla #919239 (https://bugzilla.suse.com/show_bug.cgi?id=919239)

**Comment by yuezh** [comment]
@rjschwei What's the version of SUSE and waagent?

**Comment by rjschwei** [comment]
2.0.11

Any distribution, SLES 11 SP3, or SLES 12

**Comment by yuezh** [comment]
@rjschwei I didn't meet the issue you descripted on SLES 11 SP3. Here are my steps:
service waagent start
exit
The ssh session ended normally.

**Comment by bear454** [comment]
@yuezh You can reproduce by stopping any running waagent on a machine, and running
```
waagent -daemon
```

**Comment by SuperScottz** [comment]
@yuezh Could you please have a try to see if it could be reproduced?

**Comment by szarkos** [comment]
The agent doesn't actually "daemonize" at all, in that it doesn't do the typical double-fork thing and detach from the console when it enters the Agent.Run() loop.  That's why the agent still runs in the foreground when you run "waagent -daemon," and why the '&' is required in the init scripts.

The trouble is that even running the agent in the background using the '&' does properly detach the agent from the terminal.  So for example, trying to start the agent remotely causes a hang:

ssh ostc@MY-VM.cloudapp.net 'sudo /usr/sbin/waagent -daemon &'
.... <hangs forever>

**Comment by yuezh** [comment]
We will implement real "daemonize" in version 2.1

**Comment by ahmetalpbalkan** [comment]
@yuezh does 2.1 fix this issue? If so, please close.

**Comment by hglkrijger** [comment]
closing, due to lack of activity. if this is still a feature request, please reopen.

**Comment by rjschwei** [comment]
I tested 2.1 with SLES 11 SP4 where this is aproblem as SysV init handles file descriptors differently than systemd (SLES 12 and later) and observed the same problematic behavior.
