### ISSUE TITLE
Allow swap to use device other then /dev/sdb

### ISSUE THREAD

**Issue by ChrisJergens** [Azure/WALinuxAgent#708]
By all my reading it seems that waagent expects /dev/sdb to be for it's use.  But when preparing a image for Azure, we have already used sdb and sdc for data disks.  Therefore EnableSwap never works because /dev/sdb is not available.  Please allow a more flexible configuration for the swap disk/partition choice.  Or tell me how please. :)

**Comment by brendandixon** [comment]
@ChrisJergens The agent, despite appearances, does not reserve or assume top use `/dev/sdb`. The agent does know that the first IDE / SCSI device is provided by Hyper-V as the resource volume and that volume is often assigned (by `udev`, the kernel) `/dev/sdb`.

Hyper-V has two reserved device IDs: `00000000-0000-8899-0000-000000000000` and `00000000-0001-8899-0000-000000000000`. The `azurelinuxagent.common.osutil.default.py#device_for_ide_port` searches for the second (since that is where Hyper-V attaches the resource volume). It then digs out the device name (e.g., `/dev/sdb`) and mounts it as the resource volume (usually at `/mnt/resource`).

Generally, especially since the advent of `udev`, assuming fixed device names is dangerous and will often not work. LUNs are stable as are the UUIDs (aka BLKIDs).

I hope this helps.

**Comment by ChrisJergens** [comment]
Hello,
If you look at the words you used though, there does seem to be some assumptions going on. How does the agent 'know' the purpose of any volume?  What do you mean 'usually', what else could it be/how?
The point of this Issue though is not an argument about any assumptions though, it's about making it configurable so I can tell it to use something else.  

If I have a machine with three devices already configured for other uses, and want to move it into Azure, it can not be configured with swap by the agent.

So how can I tell the agent to use a specific device instead of it just knowing and usually doing something else.

**Comment by brendandixon** [comment]
@ChrisJergens The assumptions made by the agent are not assumptions, they are the contract the VM has with Hyper-V when running in Azure. It's how things work.

I suggest you evaluate other means of selecting device names. This is common challenge in Linux.

**Comment by ChrisJergens** [comment]
More like requirements I suppose.  Would that be more accurate?
Requires an available disk device which must be the 2nd device in order.
Requires an available directory at /mnt/resource to mount said device.

It's not a challenge for Linux which can be configured any number of ways.  I'm just trying to avoid having to rebuild an entire server platform because of waagent swap.

Thanks for your time. Bye.
