### ISSUE TITLE
[2.2.11] There are too many log print to /var/log/waagent.log

### ISSUE THREAD

**Issue by yuhuijiang** [Azure/WALinuxAgent#711]
Hi there,
I found that WALA print too many log in /var/log/waagent.log,now

2017/05/12 15:47:23.209433 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/05/12 15:47:27.390004 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/05/12 15:47:30.591457 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/05/12 15:47:33.762246 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/05/12 15:47:37.947431 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=

new release(2.2.11) add an event log in azurelinuxagent/ga/update.py (line 263-268)

> add_event(
>                     AGENT_NAME,
>                     version=CURRENT_VERSION,
>                     op=WALAEventOperation.ProcessGoalState,
>                     is_success=True,
>                     duration=elapsed_milliseconds(utc_start))
> 

But I think too many(maby be 3-4 second every item) this kind of log is useless.
And it maybe waste resource.

B&R,
Yuhui

**Comment by enihcam** [comment]
+1

Additionally, how to change the log level of waagent?

**Comment by brendandixon** [comment]
@yuhuijiang @enihcam These logs are meant to be used for diagnosis by our team. We probably should reduce the frequency of this message. (We changed our polling rate to improve other performance and the increased messages were an unintended side-effect.) While you can change the log settings via the /etc/waagent.conf file, we strongly discourage it since doing so would inhibit our ability to diagnosis issues.

**Comment by brendandixon** [comment]
We should:

* Reduce the frequency of the ProcessGoalState message
* Reduce the frequency of the HeartBeat message
* Always write a log message whenever we receive a new goal state
