### ISSUE TITLE
Agent Upgrades During Enable

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#749]
A customer logged an [issue](https://github.com/Azure/custom-script-extension-linux/issues/95) against CustomScript. She noticed that her deployment scripts were not executing as part of a Terraform build.  It looks like the agent upgrade happens while the extension is in the middle of enable, but I could be wrong.  CustomScript tries to protect itself by double forking, but there may be a bug there too.

The customer is running CentOS 7.3, and has tried 7.1 and 7.2.  The base image version is 2.2.11, and the agent upgrades to 2.2.12.  See the opening [issue](https://github.com/Azure/custom-script-extension-linux/issues/95) for logs.

What is the expected behavior in this case?  Will the agent wait for the enable command to complete before restarting?  If it does, this probably indicates a bug in the extension.  The extension is trying to be cute, and allow for long running scripts by using a double fork.

**Comment by brendandixon** [comment]
@boumenot I do not believe there is much we can do here. The agent will not update itself while installing or enabling an extension. In this case, since `enable` returned, the agent believes it is safe to proceed.

The customer could author their scripts (e.g., leave a sentinel on disk) to implement idempotancy during the second call to `enable`.
