### ISSUE TITLE
WAlinuxAgent-2.2.14.1 failed to start on ubuntu16.04

### ISSUE THREAD

**Issue by JuneZhao** [Azure/WALinuxAgent#804]
Filed to start walinuxagent
root@vpnfirewall:/home/vpnuser/WALinuxAgent# waagent -version
WALinuxAgent-2.2.14.1 running on ubuntu 16.04
Python: 2.7.12
Goal state agent: 2.2.14.1

root@vpnfirewall:/home/vpnuser/WALinuxAgent# service walinuxagent status
● walinuxagent.service - Azure Linux Agent
   Loaded: loaded (/lib/systemd/system/walinuxagent.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2017-07-18 15:54:27 CST; 10min ago
  Process: 12358 ExecStart=/usr/bin/python3 -u /usr/sbin/waagent -daemon (code=exited, status=1/FAILURE)
 Main PID: 12358 (code=exited, status=1/FAILURE)

Jul 18 15:54:27 vpnfirewall systemd[1]: walinuxagent.service: Main process exited, code=exited, status=1/FAILURE
Jul 18 15:54:27 vpnfirewall systemd[1]: walinuxagent.service: Unit entered failed state.
Jul 18 15:54:27 vpnfirewall systemd[1]: walinuxagent.service: Failed with result 'exit-code'.
Jul 18 15:54:27 vpnfirewall systemd[1]: walinuxagent.service: Service hold-off time over, scheduling restart.
Jul 18 15:54:27 vpnfirewall systemd[1]: Stopped Azure Linux Agent.
Jul 18 15:54:27 vpnfirewall systemd[1]: walinuxagent.service: Start request repeated too quickly.
Jul 18 15:54:27 vpnfirewall systemd[1]: Failed to start Azure Linux Agent.

from journalctl it shows me 
Jul 18 15:53:25 vpnfirewall systemd[1]: Failed to start Azure Linux Agent.
Jul 18 15:54:24 vpnfirewall systemd[1]: Stopped Azure Linux Agent.
Jul 18 15:54:24 vpnfirewall systemd[1]: Started Azure Linux Agent.
Jul 18 15:54:25 vpnfirewall python3[12271]: Traceback (most recent call last):
Jul 18 15:54:25 vpnfirewall python3[12271]:   File "/usr/sbin/waagent", line 31, in <module>
Jul 18 15:54:25 vpnfirewall python3[12271]:     import azurelinuxagent.agent as agent
Jul 18 15:54:25 vpnfirewall python3[12271]: ImportError: No module named 'azurelinuxagent'
Jul 18 15:54:25 vpnfirewall systemd[1]: walinuxagent.service: Main process exited, code=exited, status=1/FAILURE
Jul 18 15:54:25 vpnfirewall systemd[1]: walinuxagent.service: Unit entered failed state.
Jul 18 15:54:25 vpnfirewall systemd[1]: walinuxagent.service: Failed with result 'exit-code'.
Jul 18 15:54:25 vpnfirewall systemd[1]: walinuxagent.service: Service hold-off time over, scheduling restart.

i tried to depvision it but also failed
root@vpnfirewall:/home/vpnuser/WALinuxAgent# python3 /usr/sbin/waagent -deprovision
Traceback (most recent call last):
  File "/usr/sbin/waagent", line 31, in <module>
    import azurelinuxagent.agent as agent
ImportError: No module named 'azurelinuxagent'

kernel 
root@vpnfirewall:/home/vpnuser/WALinuxAgent# uname -r
4.11.9-041109-generic

I have tried apt-get and source code installation all failed.

**Comment by brendandixon** [comment]
@JuneZhao We test the agent regularly, even 2.2.14.1, on many distributions, including Ubuntu 16.04. It runs fine.

The messages you've included indicate that the agent is not correctly installed:

```
File "/usr/sbin/waagent", line 31, in 
import azurelinuxagent.agent as agent
ImportError: No module named 'azurelinuxagent'
```

I'm guessing you tried to install from Github directly. We do not recommend doing so unless you are well aware of the subtleties of the distribution. For example, on Ubuntu 16.04, Canonical installs the agent to run under Python3. Correctly hand-installing requires installing the agent using Python3 *and* modifying the "shebang" line of `/usr/sbin/waagent` to reference Python 3.

Because it can be tricky, we only support installations from a vendor's repository onto a clean image. You may be able to force install from the repository to correct the broken installation.

Lastly, 2.2.14.1 is an *internal* test drop, not an official release. If you find bugs, we'd like to know, but we do not support 2.2.14.1 running in production.

**Comment by JuneZhao** [comment]
@brendandixon  Hi I tried to run apt-get install walinuxagent without issue but failed to start that is where i  git clone repository and install with python --setup.py. Both method installed  the latest version so I am not sure how to install a stable one.

The OS is from Azure marketplace we have upgraded the kernel previously so I am not sure what can be done to recover the agent since it lost all communication with azure

**Comment by brendandixon** [comment]
@JuneZhao Broken installations of any package are difficult to repair. However, I believe you *may* be able to fix your installation by using the `--fix-broken` option of `apt-get`:

```
sudo apt-get --fix-broken install walinuxagent
```

You may want to begin by fully removing the agent and then re-installing through `apt-get`. Since Python PIP does not support an `uninstall` verb, you'll need to remove the files manually. This -- https://stackoverflow.com/questions/1550226/python-setup-py-uninstall -- describes the process. I would do that first, then run `sudo apt-get remove walinuxagent`.  Finally, re-install the agent using the command above.

I hope this helps!

**Comment by JuneZhao** [comment]
Appreciated. I tried the steps that you showed to me but it is not working.
I tried an fresh install with python3  --setup.py to mitigate the issue

**Comment by brendandixon** [comment]
@JuneZhao I am sorry that the steps did not help. As I mentioned, fixing broken package installations is difficult. Without me physically making the changes, I don't have any more advice. :(
