### ISSUE TITLE
Calling wire server failed: 503 - http://168.63.129.16/machine/?comp=goalstate

### ISSUE THREAD

**Issue by redhatjobin** [Azure/WALinuxAgent#821]
The waagent had faced some network issue and it was not able to reach the the URL (http://168.63.129.16/machine/?comp=goalstate).
It has been 15 days for me now and the service never retried for the URL.
I had to manually restart the waagent service to get it back.

**Comment by brendandixon** [comment]
@redhatjobin If you can recreate this, we could possibly debug via the logs. The agent should periodically retry. If you cannot recreate it, then there is not much we can do at this time.

**Comment by redhatjobin** [comment]
@brendandixon as per the waagent logs, there was no retry for 15 days.

It is very easy to recreate, just create a network connectivity issue with 168.63.129.16 (disable outgoing port 80 on the VM) and see the logs.

Im on RHEL7.3 on Azure.

**Comment by brendandixon** [comment]
@redhatjobin I spun up a RedHat 7.3 image and added an outbound rule to block access to all IPs. The image ran fine and the agent continually checked (as evidenced by error messages stating it could not reach host services).

Since I cannot recreate this, the only path forward is if you can and then to have me examine the logs. I suspect that, in your case, the agent crashed for some reason and the system failed to restart it. Only the logs can tell us for certain.

I'll leave this open for now.

**Comment by brendandixon** [comment]
@redhatjobin I am going to go ahead and close this since we cannot recreate the issue. If you *can* recreate it, please re-open this issue with the agent logs (e.g., /var/log/waagent.log) so we can figure it out. Thank you.

**Comment by redhatjobin** [comment]
@brendandixon could you please tell me which waagent version you are running on?

**Comment by brendandixon** [comment]
@redhatjobin I tested with the latest version in the RedHat repository, which is 2.2.14.
