### ISSUE TITLE
waagent ovf-env.xml file missing after 'waagent -deprovision+user -force'

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/WALinuxAgent#826]
I prepare VHD-image of my VM.
After running 'waagent -deprovision+user -force' the file /var/lib/waagent/ovf-env.xml is deleted and is not recreated.
When I try to create VM from VHD-image VMAccessForLinux fails in creating new user.
I was able to get the disk of this VM, mount it to running VM and look at /var/log/waagent.log file - it throws an error of missing '/var/lib/waagent/ovf-env.xml' file.
How to fix it?

**Comment by brendandixon** [comment]
@alexeyshishkin01 It is not a bug. The Azure fabric layer creates and provides to the VM, by means of a mounted "DVD", the `ovf-env.xml` file. It is present *only* on first boot of a new VM (that is, during provisioning) and contains the information needed to bring the VM "up" within Azure.

Deprovisioning removes the file because a deprovisioned VM is *intended* to be the basis for new VMs (which will receive their own copy of `ovf-env.xml`).

I hope this helps.

**Comment by alexeyshishkin01** [comment]
thanks for that, the thing is the problem exists and can be easily repeated.
a)
- create 1st VM from Azure CentOS image of latest 7.3 version
- create a snapshot of 1st VM's disk
- create a disk from the snapshot
- create 2nd VM by attaching the disk
- generalize 2nd VM
- create an image from 2nd VM's disk
b)
- if I create 3rd VM from the image - it works OK
c)
- if I grant access to 2nd VM's disk, download it as VHD-file, upload the VHD-file back to Azure and try to create 3rd VM from the VHD file it fails
d)
- if I create a snapshot of failed VM's disk, create new disk from it and attach it to running VM I can look at /var/log/waagent.log file of failed VM - it claims about missing /var/lib/waagent/ovf-env.xml file and hence cannot create new user to login to failed VM

**Comment by brendandixon** [comment]
@alexeyshishkin01 Any VHD used as the basis for a new VM *must* be de-provisioned by executing `waagent -deprovision` or `waagent -deprovision+user` (the latter removes the user account as well). These commands remove the files by which the agent determines if the VM is provisioned (that is, ready for use in Azure). The `ovf-env.xml` file is just one of those. Other clean-up is also required so the VHD will work. Both commands perform all that is necessary.

The error message above suggests that the VHD was not correctly de-provisioned, causing the agent to believe it should already have the `ovf-env.xml` file.

The best process to create a VHD for re-use is to first create a new VM (say, from CentOS 7.3), make your changes, then run `waagent -deprovision` from the command line. Capture the backing VHD and use it to create as many new VMs as you desire. That should work fine.

**Comment by alexeyshishkin01** [comment]
that's the issue: of course I use 'sudo waagent -deprovision+user -force' in both cases: b) and d) (see above)
but in d) case I cannot create user of new VM due to missing /var/lib/waagent/ovf-env.xml file and I has to copy it to /etc and change /usr/lib/systemd/system/waagent.service to add ExecStartPre with the 'cp /etc/ovf-env.xml /var/lib/waagent/ovf-env.xml'

**Comment by brendandixon** [comment]
@alexeyshishkin01 The Azure fabric layer provides the `ovf-env.xml` file during VM provisioning and the agent, if it *believes* it is provisioning, copies the file (see https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/pa/provision/default.py#L76). Either the VHD was not correctly de-provisioned *or* (much less likely) the Azure fabric layer is failing to provide the file on the mounted DVD.

The specific log messages will direct you to the code raising the error. That, in turn, will establish which case it is.

I hope this helps!

**Comment by alexeyshishkin01** [comment]
VHD was de-provisioned the standard way, which is described in https://docs.microsoft.com/pdfstore/en-us/Azure.azure-documents/live/virtual-machines/linux.pdf:
- sudo waagent -deprovision+user -force
- exit
- az vm deallocate
- az vm generalize
I can reproduce the issue (it takes time to download/upload VHD file) and can get whatever log files needed for troubleshooting.
Pls. let me know what are those log files?

**Comment by brendandixon** [comment]
@alexeyshishkin01 If you can reliably recreate the issue, we would need a couple of things:

* Preferably the SubscriptionID, Resource Group Name, Region, and VM name of the failing VM (please do not, in this case, delete the VM) or
* All of the agent log files (e.g., logs named /var/log/waagent.log and related).

Additionally, we would need to see the VHD which is the base for the VM. If possible, I'd like to mount it and examine its initial state.

**Comment by alexeyshishkin01** [comment]
pls. find attached the file with commands to reproduce the issue
[waagent-test.txt](https://github.com/Azure/WALinuxAgent/files/1198786/waagent-test.txt)

pls. feel free to ask for more information to troubleshoot the issue

**Comment by alexeyshishkin01** [comment]
I also updated the file with creation VM from the image - it works all right.
[waagent-test.txt](https://github.com/Azure/WALinuxAgent/files/1198894/waagent-test.txt)

So, what I have is:
- VM creation from image works
- VM creation from VHD-file, which was created from the same disk as image, doesn't work.

**Comment by alexeyshishkin01** [comment]
any comments? have you been able to look at my file(s)? any more info needed? just let me know. thanks!

**Comment by alexeyshishkin01** [comment]
any news?

**Comment by brendandixon** [comment]
@alexeyshishkin01 I apologize for being slow; we've been busy. I also appreciate the command script you sent. However, to make progress I need the following for an active VM: SubscriptionID, Resource Group Name, Region, and VM name. The attached script did not contain the Subscription ID or the VM is deleted. If you provide these values for an active (not deleted VM), we can look at the logs and assist.

**Comment by alexeyshishkin01** [comment]
ok, thanks, I can provide requested info (SubscriptionID, Resource Group Name, Region, and VM name).
but does it mean you cannot run my script in your environment to reproduce the issue?
or the script run in your environment doesn't reproduce the issue?
P.S.
one more thing I've noticed:
- I create generalized and deprovisioned VM
- this VM has /etc/ovf-env.xml file with HostName of 'localhost.localdomain'
- this VM has modified script /usr/lib/systemd/system/waagent.service with additional line of 'ExecStartPre=/usr/bin/cp -f /etc/ovf-env.xml /var/lib/waagent/ovf-env.xml'
- after that I create an image and VHD-file from this VM's disk
- now I create VM1 from the image and VM2 from VHD file
- after VM1 and VM2 start I see the difference between /var/lib/waagent/ovf-env.xml in these VMs - VM1's /var/lib/waagent/ovf-env.xml contains HostName of VM1 'hostname' command, while VM2's /var/lib/waagent/ovf-env.xml still contains HostName of 'localhost.localdomain'
- it might mean that in case VM is created from VHD-file it's not created from scratch (mounted DVD) and modified /usr/lib/systemd/system/waagent.service simply copies it from /etc/... to /var/lib/waagent/...
- while in case VM is created from image /var/lib/waagent/ovf-env.xml is created like you described (mounted DVD) and no issue is present

pls. let me know what you think of it

**Comment by brendandixon** [comment]
@alexeyshishkin01 Thank you for the additional details. I'm going to suggest you take a different route to make progress.

The line you found in `/usr/lib/systemd/system/waagent.service` *is not* created or modified by the agent. Nor does the agent *ever* copy the `ovf-env.xml` file to `/etc`. It *only* copies the file off of the mounted DVD to `/var/lib/waagent/ovf-env.xml`. CentOS may create the `ExecStartPre` statement in `/usr/lib/systemd/system/waagent.service` when packaging their image for use in Azure (though I found no such line when I created a new CentOS 7.3 VM).

I also checked a few other distributions; none of them have or place the `ovf-env.xml` file into `/etc`. I also created a CentOS 7.3 image (based on RogueWave, since you did not specify): It did not have `/etc/ovf-env.xml` or any reference to the file in any systemd unit.

As I mentioned much earlier in this thread, the agent depends on Azure fabric to attach an ISO (DVD) that contains the `ovf-env.xml` file. The agent (and `cloud-init` for Ubuntu systems) copies the file from the ISO to its own directory (i.e., `/var/lib/waagent/ovf-env.xml`). Further, it will only look for and copy the file during provisioning (aka first boot). If the agent (or `cloud-init`) believes the VM is provisioned, it will not look for or copy the file. (Provisioned state is tracked by a sentinel file -- `/var/lib/waagent/provisioned` -- the agent writes.) De-provisioning prepares the underlying VHD for use as a new image by removing these sentinel files (and other traces).

Nothing in our discussion has identified an agent issue. I sympathize with your problem, but do not believe we are the right team to assist given your latest data. I encourage you to contact Azure Support (https://azure.microsoft.com/en-us/support/options/?v=17.33) or CentOS for additional assistance. I apologize that we've not been able to resolve your problem, but I do believe the teams I've recommended can.

I hope this helps.

**Comment by alexeyshishkin01** [comment]
thanks for the explanation - additional line of 'ExecStartPre=/usr/bin/cp -f /etc/ovf-env.xml /var/lib/waagent/ovf-env.xml' in the script /usr/lib/systemd/system/waagent.service has been added by me, otherwise I was not able to create a user in new VM due to the error: 'file /var/lib/waagent/ovf-env.xml is not found'

**Comment by brendandixon** [comment]
@alexeyshishkin01 Ok, but, again, the agent *does not* put the file in `/etc`. Further, the agent *will* look for the `ovf-env.xml` file *if* properly de-provisioned.

**Comment by alexeyshishkin01** [comment]
I understand, it was me who put it into /etc just before host gets deprovisioned+generalized in order not to   get 'missing /var/lib/waagent/ovf-env.xml file' error
Pls. let me create new VM for the demo, I had to remove previous one.

**Comment by alexeyshishkin01** [comment]
pls. find attached the file with the commands executed
requested info:
SubscriptionID - 0a0b3b19-779e-4738-92f9-c1bd31d4d78d
Resource Group Name - myresourcegroup
Region - northeurope
name of VM created from image (success) - imagevm
name of VM created from VHD-file (failure) - myvm
pls. let me know if you need more information about the issue
[waagent-test.txt](https://github.com/Azure/WALinuxAgent/files/1274234/waagent-test.txt)

**Comment by alexeyshishkin01** [comment]
any news?

**Comment by brendandixon** [comment]
@alexeyshishkin01 There is nothing more I can do here. There is no issue with the agent. As I suggested above, you are best off contacting Azure Support. They are in the best position to put you in touch the proper teams. I hope this helps.

**Comment by alexeyshishkin01** [comment]
I see, thanks

**Comment by alexeyshishkin01** [comment]
the issue is reproduced both on CentOS and RHEL, 7.3 and 7.4 version
could you pls. confirm my way of VM deprovision is correct? (pls. see the commands scripts)?
if so it almost for sure will mean a bug either in WALinuxAgent or in Azure
