### ISSUE TITLE
Backup failure alert has been activated

### ISSUE THREAD

**Issue by r1ckyfl0w** [Azure/WALinuxAgent#871]
# tail -f /var/log/waagent.log
2017/09/01 12:49:09.601321 INFO WALinuxAgent-2.2.15 waiting for orphan process 4035 to terminate
2017/09/01 12:49:12.605202 INFO WALinuxAgent-2.2.15 waiting for orphan process 4035 to terminate
2017/09/01 12:49:15.609147 INFO WALinuxAgent-2.2.15 waiting for orphan process 4035 to terminate
2017/09/01 12:49:18.613089 INFO WALinuxAgent-2.2.15 waiting for orphan process 4035 to terminate
# ps ax | grep 4035
 4035 ?        S      1:43 [kworker/0:1]
# systemctl status waagent
● waagent.service - LSB: WindowsAzureLinuxAgent
   Loaded: loaded (/etc/init.d/waagent)
   Active: active (running) since Fri 2017-09-01 12:47:46 AST; 1h 37min ago
  Process: 24824 ExecStop=/etc/init.d/waagent stop (code=exited, status=0/SUCCESS)
  Process: 26349 ExecStart=/etc/init.d/waagent start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/waagent.service
           ├─26355 python /usr/sbin/waagent -daemon
           └─26361 python -u bin/WALinuxAgent-2.2.15-py2.7.egg -run-exthandlers

Sep 01 12:47:46 MoodleWeb.unapec.edu.do waagent[26349]: Starting WindowsAzureLinuxAgent....
Sep 01 12:47:46 MoodleWeb.unapec.edu.do systemd[1]: Started LSB: WindowsAzureLinuxAgent.
# python --version
Python 3.4.2
# waagent --version
WALinuxAgent-2.2.13 running on debian 8.7
Python: 2.7.9
Goal state agent: 2.2.15

![image](https://user-images.githubusercontent.com/29577146/29983004-e9e3b9b6-8f21-11e7-9234-81796e7c1d6b.png)

**Comment by brendandixon** [comment]
@r1ckyfl0w There is not enough data here to determine the error. The messages above from `/var/log/waagent.log` are not errors; they merely reflect that the child process is likely in a long sleep. If they continue too long, then the parent will forcibly kill the child.

However, since 2.2.15 was just released, you must have installed it directly from Github vs. pulling it from the vendor's repository. We do not support doing so since each distribution has its own requirements and changes necessary for the agent to successfully run.

I suggest you revert back to the most current agent available in the distribution vendor's repository. I suspect you'll then be fine.

I hope this helps.
