### ISSUE TITLE
mount: no medium found on /dev/sr0 with custom linux image

### ISSUE THREAD

**Issue by kank21** [Azure/WALinuxAgent#927]
Hi All,

I have a custom linux image.
I am getting following error in waagent.log:
mount: no medium found on /dev/sr0

Kindly help.

Regard,s
Kanika

**Comment by brendandixon** [comment]
@kank21 It is likely, since we've not had other reports on issues with creating or using custom images, that your image has issues. The following articles in our documentation should help. If not, then I suggest you contact Azure Support. This repository only hosts bug reports against the agent and the message appearing in the log is not a bug in the agent, but describes what the agent "saw" when starting the VM. I hope this helps.

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/upload-vhd
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/capture-image
