### ISSUE TITLE
There shoud be an prompt in `systemctl status waagent.service`

### ISSUE THREAD

**Issue by yuhuijiang** [Azure/WALinuxAgent#934]
If we don't  use default path of WALA configuration file(/etc/waagent.conf),rather than using a customized path(such as '/home/waagent.conf').And then we didn't copy/move the configuration file from default path to the customized path (such as from /etc/ to /home).And then we start WALA by 'systemctl start waagent',and then we check if WALA is running.But it not run.And we check WALA service status by 'systemctl status waagent.conf',and there is no an prompt information to tell us why the service not run.
The root cause is ,WALA will check whether the configuration file exists.If it exists,and WALA daemon will go on ,but if not exist,WALA will exit and print some information to console/screen,but when we use systemctl to manage WALA ,this prompt information will not output to systemctl status waagent.conf.
So if our customer customizes WALA's configuration file path but they forget to copy/move configuration file to the right path,there will be some difficulties for them.

**Comment by brendandixon** [comment]
@yuhuijiang The problem is the agent needs the configuration file to set-up logging options. It creates its general purpose logger gets after loading the configuration. The error the agent emits, in this case, is written to `STDOUT`, we could write it to `STDERR` as well, but not much more than that. `systemd` should be able to capture this output for diagnosis.
