### ISSUE TITLE
Provisionning is not happening

### ISSUE THREAD

**Issue by moulip** [Azure/WALinuxAgent#978]
Hi,

I have an issue which drives me a bit crazy ! I'm trying to create a VM from a custom image. It's based on a Debian Jessie 8.9. I have installed the agent with the zip file. When I create the VM on Azure, it can't be provisioned because it can't mount the DVD image I have this in the Boot diagnostics 
`2017/12/20 10:39:24 ERROR:No DVD device detected, unable to provision`

Please find below my waagent.conf which is the default one except that I changed the path for CDROM to see if that changes anything, which clearly is not the case.
```
Provisioning.Enabled=y
Provisioning.UseCloudInit=n
Provisioning.DeleteRootPassword=y
Provisioning.RegenerateSshHostKeyPair=y
Provisioning.SshHostKeyPairType=rsa
Provisioning.MonitorHostName=y
Provisioning.DecodeCustomData=n
Provisioning.ExecuteCustomData=n
#Provisioning.PasswordCryptId=6
#Provisioning.PasswordCryptSaltLength=10
Provisioning.AllowResetSysUser=n
ResourceDisk.Format=y
ResourceDisk.Filesystem=ext4
ResourceDisk.MountPoint=/mnt/resource
ResourceDisk.EnableSwap=n
ResourceDisk.SwapSizeMB=0
ResourceDisk.MountOptions=None
Logs.Verbose=n
OS.EnableFIPS=n
OS.RootDeviceScsiTimeout=300
OS.OpensslPath=None
#OS.SshClientAliveInterval=180
OS.SshDir=/etc/ssh
#HttpProxy.Host=None
#HttpProxy.Port=None
#DetectScvmmEnv=n
#Lib.Dir=/var/lib/waagent
#DVD.MountPoint=/media/cdrom0
#Pid.File=/var/run/waagent.pid
#Extension.LogDir=/var/log/azure
#Home.Dir=/home
#OS.EnableRDMA=y
#AutoUpdate.Enabled=y
#AutoUpdate.GAFamily=Prod
#EnableOverProvisioning=n
#OS.AllowHTTP=n
OS.EnableFirewall=y
```

**Comment by hglkrijger** [comment]
Which version of the agent are you running? Could you provide the content of `/var/log/waagent.log`? If possible please update to the latest version, it should have more info regarding ISO mount failures.

**Comment by moulip** [comment]
Hi,

Thanks for answering me. I can't have access to the VM due to the
failed provisioning, the SSH keys have not been created.
I have tried another way to create the VM. I have uploaded a custom VHD
 then from there I have installed the agent using apt, and theh
deallocating, generalizing and capturing the image, from which I have
tried to create a new VM.
Now I have the following in the bootdiag:

Error mounting dvd: [000007] Failed to get dvd device from /dev
Inner error: The following devices were found, but none matched the
pattern [(sr[0-9]|hd[c-z]|cdrom[0-9]|cd[0-9])]: ['dm-7', 'dm-6', 'dm-
5', 'dm-4', 'dm-3', 'dm-2', 'dm-1', 'sg1', 'sg0', 'fb0', 'vcsa6',
'vcs6', 'vcsa5', 'vcs5', 'vcsa4', 'vcs4', 'vcsa3', 'vcs3', 'vcsa2',
'vcs2', 'snd', 'vhost-net', 'uhid', 'vhci', 'vfio', 'uinput', 'ppp',
'net', 'loop-control', 'btrfs-control', 'cuse', 'fuse', 'mqueue',
'hugepages', 'initctl', 'log', 'shm', 'autofs', 'vg00', 'dm-0',
'mapper', 'sda3', 'sda2', 'sda1', 'disk', 'sdb1', 'sdb', 'sda',
'block', 'fd0', 'rtc', 'bsg', 'char', 'stderr', 'stdout', 'stdin',
'fd', 'core', 'pts', 'memory_bandwidth', 'network_throughput',
'network_latency', 'cpu_dma_latency', 'cpu', 'mcelog', 'vmbus', 'rtc0',
'psaux', 'input', 'hpet', 'ttyS3', 'ttyS2', 'ttyS1', 'ttyS0', 'ptmx',
'snapshot', 'tty63', 'tty62', 'tty61', 'tty60', 'tty59', 'tty58',
'tty57', 'tty56', 'tty55', 'tty54', 'tty53', 'tty52', 'tty51', 'tty50',
'tty49', 'tty48', 'tty47', 'tty46', 'tty45', 'tty44', 'tty43', 'tty42',
'tty41', 'tty40', 'tty39', 'tty38', 'tty37', 'tty36', 'tty35', 'tty34',
'tty33', 'tty32', 'tty31', 'tty30', 'tty29', 'tty28', 'tty27', 'tty26',
'tty25', 'tty24', 'tty23', 'tty22', 'tty21', 'tty20', 'tty19', 'tty18',
'tty17', 'tty16', 'tty15', 'tty14', 'tty13', 'tty12', 'tty11', 'tty10',
'tty9', 'tty8', 'tty7', 'tty6', 'tty5', 'tty4', 'tty3', 'tty2', 'tty1',
'vcsa1', 'vcs1', 'vcsa', 'vcs', 'tty0', 'console', 'tty', 'grsec',
'kmsg', 'urandom', 'random', 'full', 'zero', 'port', 'null', 'mem',
'vga_arbiter']

**Comment by hglkrijger** [comment]
Is this a custom kernel by chance? Have you included the drivers? The device list I see from the logs you included do not seem to list a DVD device, and the agent is looking for one of these:
```
(sr[0-9]|hd[c-z]|cdrom[0-9]|cd[0-9])
```
Since this does not appear to be an agent issue, but instead a driver issue, I am closing this issue. Feel free to reopen if you have additional agent issues.

**Comment by szarkos** [comment]
In case this helps others searching about this issue - if you are just creating an image from a standard distribution and not modifying the kernel, then you should already have the drivers you need.  Of course double check that you're not blacklisting any necessary drivers, such as ata_piix an udf.

Another reason one can hit this error is if you mistakenly create a "specialized" VM, which will not undergo provisioning and thus will not have a DVD device even attached.  This is useful when restoring a VM that has already been provisioned, i.e. from a backup.  In this case you would use the "--attach-os-disk" flag with the CLI tools, i.e.:

    az vm create .... --attach-os-disk myDisk

However, most likely you really wanted to create a VM from a "generalized" disk, so that the DVD is attached and the Azure agent provisions a new user, etc.  In this case you need to use the "--image" flag:

   az vm create .... --image MyImage

Some additional docs to help here:
https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/capture-image
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/upload-vhd
